### ISSUE TITLE
Issues with dialing device

### ISSUE THREAD

**Issue by Austin5003** [McJtyMods/RFToolsUtility#1]
The device is misspelled as "dailing" device, teleportation doesn't work across dimensions, and the tooltips for transmitters/receivers move incorrectly when the mouse moves (inverted Y axis)

Also, you should put a link to the issues on the curseforge page

**Comment by McJty** [comment]
I'll check these out. Thanks for reporting

**Comment by McJty** [comment]
Fixed in latest release
