### ISSUE TITLE
Cannot open crafter gui

### ISSUE THREAD

**Issue by RakSrinaNa** [McJtyMods/RFToolsUtility#10]
McJtyLib: 1.14-3.5.1.4
RFToolsBase/Power/Utility: 0.0.1.1

With the latest update, when I try to open the GUI of the crafter, I get this in the client log:
```
[Client thread/WARN] [net.minecraft.client.gui.ScreenManager/]: Failed to create screen for menu type: rftoolsutility:crafter
```

Client debug: https://pastebin.com/qJr1WAn7 (line 1688)
Server debug: https://pastebin.com/P7uDkE6s

**Comment by McJty** [comment]
Your client debug file is missing

**Comment by RakSrinaNa** [comment]
Woops sorry, edited the link.

**Comment by McJty** [comment]
Can you also specify the correct mod versions? 0.0.1.1 is not a valid version for any of my mods

**Comment by RakSrinaNa** [comment]
0.0.11 sorry, the latest one that came out yesterday if I remember well.

**Comment by McJty** [comment]
0.0.11 for what? Please be specific. Multiple mods are at work here

**Comment by McJty** [comment]
Also server or single player?

**Comment by RakSrinaNa** [comment]
Yeah right, I forgot that all the suite doesn't have all the same versions. Basically all those released yesterday and that are X.X.11.
So 0.0.11 for the utility, 1.2.11 for the power, 0.0.11 for the base, and 3.5.14 for the lib.

This is on a dedicated server, forge 28.1.96.

**Comment by McJty** [comment]
I cannot reproduce this and I also cannot find a reason for this. I'm about to release a new version of some of my mods and hopefully it fixes it

**Comment by RakSrinaNa** [comment]
Updated lib to .15 and utility to .12 and server side can't start at all. Maybe some client only related stuff?

Server log: https://pastebin.com/ciewVpv8

**Comment by RakSrinaNa** [comment]
I can open the GUI with the latest releases 👌
