### ISSUE TITLE
No recipe for destination analyzer

### ISSUE THREAD

**Issue by Gohirro** [McJtyMods/RFToolsUtility#100]
Unable to craft destination analyzer. When using give command, able to place it but does not interact with dialing device in any way. Unable to delete destinations. 

Minecraft 1.16.5
Forge 36.2.0
rftoolsbase-1.16-2.0.11
rftoolsdim-1.16-7.0.15-beta
rftoolsutility-1.16-3.1.3

**Comment by McJty** [comment]
The recipe has been added recently
