### ISSUE TITLE
Screens Not Showing Information

### ISSUE THREAD

**Issue by IKodiiI** [McJtyMods/RFToolsUtility#102]
Hey, 

Apologies if i'm just being stupid (most likely) but i'm incredibly new to the whole modded minecraft scene of things. I was trying out the screens and screen controller and processor which i got to work however whenever i enter a new module into the screens, the screen just stays black. Not sure if i'm missing another piece that displays or if something is wrong, any help is appreciated and any tips on anything may help as well ^^ 

Thanks.

**Comment by McJty** [comment]
More info please, what version, what modules are you inserting. Can you show an example?

**Comment by McJty** [comment]
Lack of information. Closing
