### ISSUE TITLE
Cannot get property EnumProperty crash

### ISSUE THREAD

**Issue by NielsPilgaard** [McJtyMods/RFToolsUtility#103]
Relayed from https://github.com/NillerMedDild/Enigmatica6/issues/3724

> Server crashed during ticking
>
> Crash report: https://gist.github.com/clienthax/62210bef61e985a15bac8c1897962554
> Latest log: https://gist.github.com/clienthax/f774411cfbc3e670b9953aec55fd96ea

rftoolsutility-1.16-3.1.3

**Comment by McJty** [comment]
How do you reproduce that? That's very weird

**Comment by clienthax** [comment]
It appeared shortly after a pack update where some biomes got swapped around, If I had to guess, it may not of got the correct block that it expected due to that

**Comment by McJty** [comment]
Is this still relevant? I have no clue how this can happen and to me it points to mismatched versions. Please close if no longer relevant or needed

**Comment by clienthax** [comment]
Probably no, not my issue here so can't close myself
