### ISSUE TITLE
Unable to lock Matter Receivers to a whitelist

### ISSUE THREAD

**Issue by OuterRealm2000** [McJtyMods/RFToolsUtility#107]
Versions:
![image](https://user-images.githubusercontent.com/89769391/145351748-f53b377a-a7ca-4d0c-b760-c4b067d9f3e2.png)

Screenshot:
![image](https://user-images.githubusercontent.com/89769391/145351729-2de9d34e-72fa-405e-b916-1f34791bd3eb.png)

When the receiver is set like this EVERYONE with a dialer can dial these dimensions

**Comment by McJty** [comment]
I figured out the problem. I will fix this
