### ISSUE TITLE
Server crash when connecting Silent Mechanism wires to a crafter

### ISSUE THREAD

**Issue by Halfdeaf** [McJtyMods/RFToolsUtility#11]
Just got this crash from a player connectin Silent's Mechanism wire to a tier 1 crafter. I'm not sure if this is you or Silent's or even Craft Tweaker

https://gist.github.com/Halfdeaf/f67c8b9818d46d09909c85527d22c083

**Comment by McJty** [comment]
It is crashing in CraftTweaker so I would start by submitting this there
