### ISSUE TITLE
[Bug]: 1.16 Environmental Controller does not work with default range configuration until range is changed

### ISSUE THREAD

**Issue by Raidobw2** [McJtyMods/RFToolsUtility#111]
## Description
The Environmental Controller does not work OOTB. If you place it down and change the redstone mode, give it a module, RF, and power it with a lever, it doesn't work.
That's not just a graphical glitch, the effects don't get applied.
If you change the range slightly, it starts to work and then you're fine for the rest of your playthrough.
On the following media I am outside the module's range, but you can see that the block is not active. I've tested this being within the range initially and after as well to be sure.
![environmental_controller](https://user-images.githubusercontent.com/17010632/147521904-447bdb7f-259f-40b8-a1de-bccbe0a2fca4.gif)

## Versions
Modpack: `FTB Academy 1.16`, `FTB OceanBlock`
Minecraft: `1.16.5`
Forge: `36.2.22`
RFToolsUtility: `rftoolsutility-1.16-3.1.2.jar` to `rftoolsutility-1.16-3.1.6.jar` (latest)
MCJtyLib: `mcjtylib-1.16-5.0.22.jar` to `mcjtylib-1.16-5.1.2.jar` (latest)
Tested with both modpacks on 2 different versions of RFToolsUtility.

## Other info
Initial report, relayed from: FTBTeam/FTB-Modpack-Issues#502
Thanks a lot in advance! :)

**Comment by McJty** [comment]
Will be fixed next release

**Comment by Raidobw2** [comment]
Quickest fix I've ever seen! Thank you very much and have a good day! :D
