### ISSUE TITLE
Filter slot in crafter

### ISSUE THREAD

**Issue by RakSrinaNa** [McJtyMods/RFToolsUtility#12]
It seems like we're able to input items into the filter slot if we're using the ITEM_HANDLER capability (I have a pipe putting items in from the right side). This is a bit annoying as the items won't be used for crafting and are taken out from the hopper below.

This happens when the input buffer is full.

Maybe should prevent this slot from being inserted with the capability, or at least make it filter for the future filter items.

**Comment by McJty** [comment]
Fixed next release
