### ISSUE TITLE
Unable to use machine infuser

### ISSUE THREAD

**Issue by Veil11** [McJtyMods/RFToolsUtility#122]
As title states, no matter what I do I can't get the machine infuser to work. I put dim shards in and try to put a machine in like the crafter that says it can be infused but it wont let me put it in the machine infuser at all.

**Comment by McJty** [comment]
First: version. I *always* need a version
Secondly: show me a screenshot of what you're trying

**Comment by notFalkon** [comment]
I can infuse machines, but it doesn't let me infuse any tier of crafter.
Version: `1.16-3.1.9`
![Shield Projector](https://user-images.githubusercontent.com/79824068/150636938-f619e7a1-e4a2-4107-8102-86ef2143f9ba.jpg)
![Crafter](https://user-images.githubusercontent.com/79824068/150637075-1f6d8fcd-0aa7-4a72-b28c-109aacd35647.jpg)

**Comment by Veil11** [comment]
im on version 1.16-3.1.9
![Screenshot (7)](https://user-images.githubusercontent.com/82344034/150649656-11957b6b-285d-44b4-86c7-4dfd94a16ad2.png)

**Comment by McJty** [comment]
Fixed in the next version for 1.16.5 and 1.18.2
