### ISSUE TITLE
Redstone reciever output has odd behavior when linked to multiple transmitters

### ISSUE THREAD

**Issue by callmeish** [McJtyMods/RFToolsUtility#123]
Not sure if this is working as intended but:

When a redstone receiver is on the same channel as two (or more) transmitters, it appears to update based on whichever transmitter most recently changed signal rather than OR-ing the transmitter inputs.

Example:
![image](https://user-images.githubusercontent.com/20137270/151105703-4d72c549-38db-4e20-841d-81b6f84bdb7d.png)
1. Place a redstone transmitter.
2. Link a redstone receiver and a second redstone transmitter to the first transmitter.
3. Place the second transmitter and the reciever.
4. Provide redstone ON signals to both transmitters (here done using levers) - the receiver also turns ON.
5. Turn one of the receiver signals to OFF - the receiver also turns OFF despite having a transmitter still set to ON.

Game version:
Minecraft 1.18.1
McJtyLib 6.0.5
RFToolsBase 3.0.1
RFToolsUtility 4.0.3

**Comment by McJty** [comment]
yes, I'm afraid that's unavoidable. The system isn't designed to do logical operations like that.

**Comment by callmeish** [comment]
Alright, no problem. Thanks for the quick response.
