### ISSUE TITLE
Crafter does not show symbol in list of recipe nor result of the craft

### ISSUE THREAD

**Issue by cholio** [McJtyMods/RFToolsUtility#124]
Forge: 39.0.43
RFToolsUtility: 1.18-3.0.4

When saving a recipe in the crafter, the list of recipes does not get updated, and there is no result shown.
Still, when the resources are in the input, it gets crafted.
Only the ingedients get stored in the recipe view.
The following recipe does indeed create wax blocks, as expected:
![rftools_crafter](https://user-images.githubusercontent.com/98484005/151231717-948a81bc-2b06-4f63-8186-1eca200311f1.jpg)

**Comment by Pultex** [comment]
same for me can not clear old recipes after update either 

the output will stay the same if you update from the older version

So three iron will always show a bucket output even if cleared

all other rftools mods where updated at the same time

**Comment by McJty** [comment]
Clear old recipes after update? What do you mean by that exactly?

**Comment by McJty** [comment]
@cholio do you press 'apply' after changing the recipe?

**Comment by Pultex** [comment]
If I try to change the recipe after updating it still shows the output recipe that was there before the update

So removing all items from the craft menu and click apply will still show the old item that is part of the recipe shown before
and changing the recipe will not craft any new recipe in that slot

Also found out that if you use JEI to add the recipe it will fill correctly and change the output

Still there is the issue the the OP stated happening unless I use JEI it will not change the output

**Comment by McJty** [comment]
Aha, I always test using JEI. I will try this out manually then. Thanks for the hint

**Comment by Pultex** [comment]
Also just to point out I am on 

Minecraft 1.16.5
forge: 1.16.5-forge-36.2.20

Rft version
mcjtylib-1.16-5.1.3
rftoolsbase-1.16-2.1.2
rftoolsutility-1.16-3.1.9

not sure if you are still updating 1.16.5 directly anymore

**Comment by McJty** [comment]
yes I am. I maintain both 1.16 and 1.18 now

**Comment by McJty** [comment]
Will be fixed in the next update for 1.16 and 1.18

**Comment by cholio** [comment]
> @cholio do you press 'apply' after changing the recipe?

Sorry for the late reply, but yes i did press apply.
