### ISSUE TITLE
Can't delete first digit in either Y level limit in  Environmental Controller.

### ISSUE THREAD

**Issue by Soonergymnast** [McJtyMods/RFToolsUtility#125]
![2022-02-07_02 12 45](https://user-images.githubusercontent.com/37964131/152749936-eea4a1f1-8c5b-4f14-99c3-2e7f0d5cb500.png)

I am currently playing on a server with the modpack Allthe Mods 7 version 0.2.37. The version of this mod that they are using is rftoolsutility-1.18-4.0.7.jar. I have placed down and powered the Environmental Controller and it works like it should except for the fact that I can't change the Y level limiter past the first digit. I can delete the second digit on both limits just fine. This is causing me a problem because I built my house on a mountain where my Y level is at 82 which I can't set the height limit past 79 or I have to set it to 700 which uses way to much power. Hope this makes sense and let me know what other information I can give to help out.

**Comment by McJty** [comment]
Move your cursor to the left and type '8' there. It just doesn't allow your second value to be smaller then the first but it's easy to get around that
