### ISSUE TITLE
Digit Block - Render Block Entity Client Crash

### ISSUE THREAD

**Issue by HellBreecher** [McJtyMods/RFToolsUtility#127]
Crash Log: https://pastebin.com/5pzimHs1

Minecraft Version: 1.18.1
Forge: 39.0.75
Java Version: 17.0.1
Mod List in crash log

I placed a Digit block on a server next to a piece of redstone (connected to a RFTools Receiver). It placed weird so I removed it and tried placing another one, when that happened I crashed along with my friend that was also in render distance of the block. 

I would try to get pictures of a way to duplicate the issue but since it crashes the game I can't do that. 

Server did not crash, so it just affects clients that are rendering the block. 

The solution we had to use was to delete our player data, get somewhat close to his base and use the /fill command to replace that block with air (thankfully crashlogs have those coordinates). We crashed several times just by getting to close to his base.

**Comment by McJty** [comment]
Fixed in the next version
