### ISSUE TITLE
Rftools Matter transmitter/receiver issues when set to "Private"

### ISSUE THREAD

**Issue by jinkhya** [McJtyMods/RFToolsUtility#13]
Versions : 
rftoolsbase-1.14-0.0.11-alpha
rftoolsutility-1.14-1.2.12-alpha
Forge 103
(modpack Enigmatica 4 if that's any useful)

Hello,
Unless I'm missing something I think the Matter transmitters and receivers are not fully working properly :

- When you set the transmitter to "private" and add your mc name to the list to allow yourself, you can no longer teleport anywhere.
- When you set the receiver to "private" and add your mc name to the list, you cannot see it in the list in the dialer anymore. (The way around this one is to leave it public, dial, and then set it to private. However if you want to interrupt the dial, you wouldn't be able to dial on it again, unless you set it back to public before doing so). If I'm not clear let me know :)

Thanks in advance,
Jin

**Comment by phit** [comment]
this is still an issue on 1.15 running rftoolsutility-1.15-2.1.3-beta

**Comment by McJty** [comment]
Fixed next release (soon)
