### ISSUE TITLE
Redstone logic block side inputs don't connect to projectRed connectors or vanilla redstone.

### ISSUE THREAD

**Issue by TenaciousLemur** [McJtyMods/RFToolsUtility#134]
The RFTools wire block does allow redstone input. Project red wires of any kind will not connect to the side inputs of the logic block. Redstone dust which is placed in a line adjacent to the side inputs will also not connect.

I am not sure if this warrants fixing as it involves interaction with another mod but there we go.

Minecraft version: 1.16.5
Forge version: 36.2.33
Mod version: rftoolsutility-1.16-3.1.12
RFtools base version: rftoolsbase-1.16-2.1.2

Project red version: ProjectRed-1.16.5-4.12.0-beta-0-[all parts]

No crashes or anything.

**Comment by McJty** [comment]
Well it works fine with redstone and redstone repeaters so no idea really
