### ISSUE TITLE
[1.16.5] Screens bigger than 1x1 become unusable if their chunk is not loaded

### ISSUE THREAD

**Issue by ChrisCrossOnGit** [McJtyMods/RFToolsUtility#135]
This issue first appeared when playing All the Mods 6 version 1.8.22 on a server that I host on the same machine. 
It's about screens that are enlarged from their 1x1 size. When leaving the general area where a screen is, the chunk gets unloaded. When coming back, the screen block (using Waila to see the block info at the top) turns from "Screen" into "block.rftoolsutility.screen_hitblock" and whatever buttons are on it become unusable. If the button stretches for the entire 3 blocks of screen length and is at the top, it is still clickable on the original 1x1 screen's position (top left).
I can access the modules inside the screen. The screen goes back to normal if I use the blue wrench on it whenever I come back, and reset its size.
https://gyazo.com/d7e4e2291c462e670d62198989eb9709 - Here is the glitched screen.
Relevant versions:
- Minecraft 1.16.5
- Forge 36.2.31
Mods:
- McJtyLib mcjtylib-1.16-5.1.4
- RFTools Base rftoolsbase-1.16-2.1.2
- RFTools Builder rftoolsbuilder-1.16-3.1.7
- RFTools Control rftoolscontrol-1.16-4.0.14
- RFTools Dimensions rftoolsdim-1.16-7.0.20-beta
- RFTools Power rftoolspower-1.16-3.0.13
- RFTools Storage rftoolsstorage-1.16-2.0.18
- RFTools Utility rftoolsutility-1.16-3.1.11
I have reproduced this issue in a save with only these (^) mods installed, outside of the modpack. Exact same forge version, too. I copied the mods from the modpack folder. Same issue. Same versions all around. The screens are connected and powered in all cases. Here's a video of the issue being reproduced in the clean save. 
https://www.youtube.com/watch?v=DVjkNGJ2KXY

**Comment by McJty** [comment]
I'll check this out soon

**Comment by McJty** [comment]
I can reproduce this

**Comment by McJty** [comment]
Will be fixed next release (soon)
