### ISSUE TITLE
Cannot change channels on redstone transmitters/receivers

### ISSUE THREAD

**Issue by Semi0ne** [McJtyMods/RFToolsUtility#138]
Issue description: There is no (obvious) way to change the channel the redstone transmitters/receivers use.

Steps to reproduce: Get a couple transmitters and a couple receivers. Link them all together on channel 1. Now try to change the channel on any of them.

Also, there is no explanation in the manual on how to change channels nor is there any information about the transmitters/receivers to be found on the wiki.

Versions:
* Modpack: FTB Academy 1.3.0
* Minecraft: 1.16.5
* Forge: 36.2.22
* McJtyLib: 1.16-5.1.2
* RFToolsBase: 1.16-2.1.1
* RFToolsUtility: 1.16-3.1.6

**Comment by McJty** [comment]
Yes, it's a bit confusing and the way to clear channels isn't actually implemented in 1.16 (put in crafting grid). I'll try to think of a better way

**Comment by McJty** [comment]
In the next version of RFToolsUtility there will be a new button in the GUI of both the receiver and transmitter to reset the channel
