### ISSUE TITLE
Game crashes after inserting syringe into spawner

### ISSUE THREAD

**Issue by MoeHunt3r** [McJtyMods/RFToolsUtility#139]
Issue description: After putting a syringe with slime in the RFTools Spawner the game crashes. When starting again everything works fine until I right click the spawner again. 

Steps to reproduce: Insert syringe into spawner

Versions:
* Minecraft: 1.18.2
* Forge: 40.1.0
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: 6.0.13
* RFTools:
- RFToolsBase 1.18-3.0.7
- RFToolsUtility 1.18-4.0.14

Possibly incompatible mods and versions: None

Relevant logs:
Crashlog: https://pastebin.com/snA67ZFM
Crashy: https://crashy.net/2JQUi9VS6IVtc7qWJklX

**Comment by McJty** [comment]
Hmm. I cannot reproduce this. Did you modify any configs? Specifically for the spawner?

**Comment by McJty** [comment]
It appears as if the tag rftoolsutility:living/living has been modified

**Comment by Gbergz** [comment]
> Hmm. I cannot reproduce this. Did you modify any configs? Specifically for the spawner?

Pack creator here, nope haven't modified anything manually.

**Comment by McJty** [comment]
Still not sure what the problem is but I'll fix this by adding division by zero protection. For the next version
