### ISSUE TITLE
crash on startup(forge-1.14.4) [There is two silent rftoolsutility and rftoolsbuilder crashes]

### ISSUE THREAD

**Issue by SDUBZ** [McJtyMods/RFToolsUtility#14]
https://github.com/blay09/CookingForBlockheads/issues/419
forge version is mentioned in issue referenced
rftoolsutility-1.14-1.2.13-alpha
rftoolsbuilder-1.14-1.2.11-alpha

**Comment by McJty** [comment]
Seems something got corrupt in the config files. Try removing the rftools config files to let them regenerate and see if that helps

**Comment by SDUBZ** [comment]
tried that still same problem

**Comment by McJty** [comment]
Since not everybody is reporting this problem there is probably some mod conflict on your end. Could you try to reproduce this with less mods?

**Comment by SDUBZ** [comment]
i got it to randomly stop outputting the error
but forge should really switch from nightconfig thing so broken
