### ISSUE TITLE
[1.18.2] Tanks Don't Accept Milk Bucket as Filter

### ISSUE THREAD

**Issue by HalcyonSeas73** [McJtyMods/RFToolsUtility#140]
RFToolsUtility version: 4.0.13
RFToolsBase version: 3.0.7
McJtyLib version: 6.0.13
Forge version: 40.1.20
Minecraft version: 1.18.2

When trying to place a Milk Bucket as a filter for a tank, it isn't accepted.

**Comment by McJty** [comment]
What pack is this? In vanilla milk is not a liquid. So unless you have another mod that makes milk an actual liquid this is normal

**Comment by HalcyonSeas73** [comment]
🤔 
My apologies, I saw `minecraft:milk_bucket' and thought it had been added by vanilla; it was added by Supplementaries instead.
