### ISSUE TITLE
Blindness Module is uncraftable

### ISSUE THREAD

**Issue by Geometer1729** [McJtyMods/RFToolsUtility#141]
The recipe for the blindness module show barrier blocks and says `Empty tag: forge:dyes/black`.
I'm playing Direwolf 20 1.18 1.2.0 which has RFToolsUtility 1.18-4.0.14

Black dye seems to have the tag `forege:dyes/black` and the same tag works fine for all the screen modules, so it seems like it can't be a typo in the tag. 
Maybe it expects the ink to have the have the nbt data the syringe has to say it needs a squid?
running `❯ag -l tag | xargs ag -l mob` seems to show that the blindness module is unique in having a recipie with a tag and a mob requirement for a syringe so I suspect that's related to the problem.

**Comment by McJty** [comment]
Investigating

**Comment by McJty** [comment]
Will be fixed in the next release

**Comment by Geometer1729** [comment]
Thanks :)
