### ISSUE TITLE
Counter Screen Module Non-Functional

### ISSUE THREAD

**Issue by joelra** [McJtyMods/RFToolsUtility#147]
The Counter Screen Module (as well as Counter Screen Plus Module) do not have recipies when viewed within JEI. While it is possible to `give` those screen modules via a command or creative, they have no function when right-clicking on a counter.

This appears to be due to those recipes being commented out in https://github.com/McJtyMods/RFToolsUtility/blob/1.16/src/main/java/mcjty/rftoolsutility/datagen/Recipes.java (lines 113-121) as well as the functionality for right clicking with the screen module being commented out in https://github.com/McJtyMods/RFToolsUtility/blob/1.16/src/main/java/mcjty/rftoolsutility/modules/screen/items/modules/CounterModuleItem.java.

Minecraft Version: 1.16.5
RFToolsUtility Version: 1.16-3.1.16

Edit: #148 created to address this issue.

**Comment by McJty** [comment]
Fixed in 1.18 and 1.19
