### ISSUE TITLE
Environmental Controller is not working

### ISSUE THREAD

**Issue by NiceClown** [McJtyMods/RFToolsUtility#149]
No settings can help me make it work. I'm using version 1.18.2 (rftoolsutility-1.18-4.0.16.jar ), on pack ATM 7 (0.4.25)

https://youtu.be/SodNr_VQXEo

**Comment by McJty** [comment]
Your height is set from 10 to 10. That's a 0-wide vertical area. Make it go from 10 to 100 for example. Or whatever Y range you want

**Comment by NiceClown** [comment]
I think I understood what the problem is, this is due to the fact that the flat world is set very low and the controller almost does not work at negative heights, when I climb to the height specified in it, it starts working, although the repeatability leaves much to be desired, sometimes the damage passes and the character dies. And the speed upgrade icon is not activated at all.

https://youtu.be/3mi2PAoGGvM
the video clearly shows that the controller behaves differently, with approximately the same behavior of the player.
