### ISSUE TITLE
[1.19.2] Fluid Level Not Displaying Properly

### ISSUE THREAD

**Issue by HalcyonSeas73** [McJtyMods/RFToolsUtility#151]
RFTools Utility version: 5.0.1
RFTools Base version: 4.0.3
McJtyLib version: 7.0.2
Forge version: 43.1.1
Minecraft version: 1.19.2

Fluid level in Tanks are not displaying properly; according to Jade, this tank is nearly full (capacity set via config); According to the block's visual level, it's minimal. 

![](https://cdn.discordapp.com/attachments/403872061568712705/1016795474369462422/unknown.png)

**Comment by McJty** [comment]
Fixed in the next update

**Comment by HalcyonSeas73** [comment]
Only partly fixed; https://cdn.discordapp.com/attachments/403872061568712705/1021170738817937448/unknown.png
