### ISSUE TITLE
Environmental Controller doesn't go below height level 3

### ISSUE THREAD

**Issue by Zelioz273** [McJtyMods/RFToolsUtility#157]
I'm pretty sure this was set in a earlier version of Minecraft since back then using it below y level 3 was pointless due to the bedrock, but the cave update brought the lower level of the world down to -64 so there is an area that the environmental controller cant reach now.

**Comment by McJty** [comment]
Version?

**Comment by Zelioz273** [comment]
1.18-4.0.19

**Comment by McJty** [comment]
I cannot reproduce this. For me it works just fine below zero. I was at -11 and my regeneration was working fine. Can you tell me how you tried this?

**Comment by Zelioz273** [comment]
Huh really? You were able to set the envrironmental controller affecting below y level 3? If u want more info, i'm on the pack sb3 where this is occuring. Using the flight module too. Is there something im doing wrong on my part then? Or sb3?

**Comment by McJty** [comment]
Well can you tell me what exactly you did? What did you fill in the gui? What modules?

**Comment by Zelioz273** [comment]
Hm, not sure if it's any help but i simply placed it down, powered by energy pipes from Pipez, and only the flight module.

**Comment by McJty** [comment]
Yes but what did you fill in the gui? What height was the environment controller at? I need these details to figure out what's wrong

**Comment by Zelioz273** [comment]
I mean i changed at settings and nothing affected it but i've tried it at y level 0 and y level 15, both not working, this is in spawn chunks if it matters, the settings currently are set to radius 50, height: minimum 3(because i cant change it), and maximum 70.

Wait i'm sorry i brought this up wrong in the first place i'm sorry, i cant change the first numbers no matter what, so the 3 and 7 are unchangable. But i was more focused on going under 3. Trying to mess with it just now, i found the only way to change it is holding backspace continously and then pressing a number, although i still cant inout negative numbers this way.

**Comment by McJty** [comment]
It's hard but it is actually possible to input negative numbers. But I'm fixing it to make it easier

**Comment by Zelioz273** [comment]
Oh u can? Huh, interesting. And nice, thanks for the quick replies and quick update on this

**Comment by McJty** [comment]
Just released a new version which fixes the negative input
