### ISSUE TITLE
Charged Porter's UI

### ISSUE THREAD

**Issue by Sunekaer** [McJtyMods/RFToolsUtility#159]
### Describe the bug

Due to the lengthy dimension name displayed in the Charged Porter's UI, only two characters of the Matter Receiver's name are shown and, once you have a handful or more set up, confusion/hilarity ensues...

GUI scale doesn't make a difference.

### Steps to reproduce

1. Set up Matter Receiver, give it name, link to it etc.
2. Open up the Charged Porter UI

### Expected behaviour

More than two characters of target name shown

### Screenshots

![Screenshot](https://gcdnb.pbrd.co/images/xNCk0dRsvTDE.png?o=1)

Versions:
* Minecraft:  1.18.2
* Forge: 40.1.82
* McJtyLib: mcjtylib-1.18-6.0.18.jar
* RFTools Utility: rftoolsutility-1.18-4.0.20.jar

**Comment by McJty** [comment]
Fixed for the next version in 1.18.2, 1.19.2, and 1.19.3 by setting the cursor at the beginning so the important name is most visible
