### ISSUE TITLE
Permanent broke

### ISSUE THREAD

**Issue by DaveRainbowin** [McJtyMods/RFToolsUtility#16]
I placed a screen controller down then placed a screen block. My game crashed and I can no longer open that world. Using 1.14.4, mod version 1.14-1.2.13 alpha

**Comment by McJty** [comment]
Bug in forge (there is a PR that is taking its time to get merged: https://github.com/MinecraftForge/MinecraftForge/pull/6337). As a workaround disable truetype in the RFTools Utility config
