### ISSUE TITLE
Crafter not remembering storage slots after shift click removal

### ISSUE THREAD

**Issue by Star-Tube** [McJtyMods/RFToolsUtility#161]
When remembering items in the crafter (I am using mk 2, might be isolated to the mk 2 or might be general) I have noticed that it sometimes forgets the slots. I have narrowed it down to happening when I shift click remove the items from the buffer.

Let me know if you need any more information about this from me.

**Comment by McJty** [comment]
Yes, that's normal. Shift-click forgets the slot
