### ISSUE TITLE
[1.16.5] Optifine visual blindness with environmental controller

### ISSUE THREAD

**Issue by HenryMaxler** [McJtyMods/RFToolsUtility#162]
Issue description: Using shaders, the environmental controller with modules creates crazy graphical glitch, blinding the player

Steps to reproduce: power the environmental controller with shaders on and you get a mess.  Sometimes it looks like a black screen with some textures on it, other times a whole lot of textures, based on the shader.

<img width="806" alt="1" src="https://user-images.githubusercontent.com/75149748/205739580-1e5fce65-3356-4f28-acfb-9e4d98a807e9.png">

Versions:
* Minecraft: 1.16.5
* Forge: 36.2.39
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: 1.16-5.1.8
* RFTools: rftoolsbase-1.16-2.1.5.jar
* rftoolsutility-1.16-3.1.16.jar

Possibly incompatible mods and versions: OptiFine_1.16.5_HD_U_G8
SEUS Renewed 1.0.1
Note the textures seem to be immersive engineering textures among others

Relevant logs, if any: 

These are the textures that commonly appear as well, except before on a black screen:

<img width="288" alt="2" src="https://user-images.githubusercontent.com/75149748/205739612-c5bdf769-40a3-4482-b333-a98334725998.png">

**Comment by McJty** [comment]
Sorry but I don't support optifine. There is no way to properly fix optifine related issues
