### ISSUE TITLE
RFTools Utility 1.18-4.0.21 Screen Controler not mineable

### ISSUE THREAD

**Issue by OutcastZeroOne** [McJtyMods/RFToolsUtility#163]
RFTools Utility 1.18-4.0.21
Forge 1.18.2-40.1.92

Place down Screen Controller, has no tool assigned for breaking it (theoneprobe-1.18-5.1.2). trying to mine it ends in the block breaking like a spawner. have to make a new controller or cheat one in to replace it. All other RFTool machines show an assigned tool and are mineable.

**Comment by McJty** [comment]
Will be fixed next release of 1.18.2. For 1.19+ it was already ok
