### ISSUE TITLE
Matter Receiver: Cannot remove player from the list

### ISSUE THREAD

**Issue by wanou067** [McJtyMods/RFToolsUtility#164]
Forge version: 1.19.2 43.2.3
Mod version: 1.19-5.0.4
Modpack: ATM8 (All the mods 8)
Server: dedicated.

Issue:
When you place a matter receiver and someone to it's whitelist, you can't remove him from the list.

After a lot of attempts I found that it's possible to remove him from the list if you click on him, then type his name in the input field 
THEN click del button.

I don't think this is the expected behavior since the del button is disabled until you click on the name of the player.

No errors are logged in client/server logs.

Steps to reproduce:
1- Place a matter receiver
2- Add an other player or yourself to the whitelist
3- Try to remove him from the list

Expected behavior:
The del button should remove the player from the list without having to type his name in the input field.

**Comment by McJty** [comment]
I'll fix this

**Comment by McJty** [comment]
Fixed next release for 1.18.2, 1.19.2, and 1.19.3
