### ISSUE TITLE
impossible to set channel i have "lost"

### ISSUE THREAD

**Issue by Zumpafuo** [McJtyMods/RFToolsUtility#167]
if i set a channel with rightclick on trasmitter (es: CH2) and next create another (CH3).. when i break the trasmitter that have CH2 i can't use this channel anymore because there is not a way to reset the incremental Channeling or set what channel i want on a trasmitter

**Comment by McJty** [comment]
I don't understand. Why can't you use that channel anymore? Just place the channel 2 transmitter down?

**Comment by McJty** [comment]
Not enough information
