### ISSUE TITLE
[1.19.2] Error in chat when teleporting close and crash when teleporting far away with a porter

### ISSUE THREAD

**Issue by Peca21** [McJtyMods/RFToolsUtility#168]
I set up my Matter receiver and a charged porter. I added a receiver to the porter list and tested the teleport.
Teleport itself worked fine but I got the "Something went wrong with the destination" message in the chat
When teleporting far away (this time 1500 blocks away from the porter), game crashed
Crash Report: https://mclo.gs/P0QYe1g

**Comment by McJty** [comment]
I'll check it out

**Comment by McJty** [comment]
Will be fixed next version
