### ISSUE TITLE
[1.18.2] Energy module can't read energy from Induction Matrix

### ISSUE THREAD

**Issue by superdarki** [McJtyMods/RFToolsUtility#169]
Hello,
I'm unable to view the energy input from my Mekanism Induction Matrix neither the Flux Point that powers it.
I know it worked fine in 1.12.2 and haven't tested it in any other version that 1.18.2.
It works with everything else but the Matrix and the Points/Plugs.
Thank you in advance !

Versions :
Forge 40.2.0
RFTools Base 3.0.9
RFTools Power 4.0.9
RFTools Utility 4.0.21

**Comment by McJty** [comment]
Report to mekanism. RFToolsUtility is following the energy capability system from Forge
