### ISSUE TITLE
Hourglass causes Screen Clock Module to fall out of time

### ISSUE THREAD

**Issue by ingrac42** [McJtyMods/RFToolsUtility#171]
Hello!

I'm building a modpack for some friends, and included RFToolsUtilities.  I've also got Hourglass as part of the pack, and I've noticed odd behavior with the screen clocks vs. world time.  I think it's because Hourglass doesn't "SKIP" the whole night, instead doing a fast forward.

I'm not asking screen clocks to go super fast, but if they could resync in the morning, that'd be great.

**Steps to recreate:**
1. Have Hourglass installed to manage sleep
2. Have a screen, screen controller, power and a clock module installed
3. Sleep!
4. Clock module keeps ticking normally while time accelerates, and only shows actual time if you get lucky

![2023-03-10 19_04_18-Minecraft_ 1 19 2 - Multiplayer (3rd-party Server)](https://user-images.githubusercontent.com/18634682/224459260-4516aa7f-6013-45b1-b19a-995baf9ed095.png)

Clock under the Minimap is correct, clock on the wall is 10 hours out in this example.

**Server info and details from a recent crash log:**

Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Linux (amd64) version 4.18.0-348.2.1.el8_5.x86_64
	Java Version: 17, AdoptOpenJDK
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), AdoptOpenJDK

	ModLauncher: 10.0.8+10.0.8+main.0ef7e830
	ModLauncher launch target: forgeserver
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.3.jar eventbus PLUGINSERVICE 
		fmlloader-1.19.2-43.2.4.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.19.2-43.2.4.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.19.2-43.2.4.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.19.2-43.2.4.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.19.2-43.2.4.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.8.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		YungsBetterDungeons-1.19.2-Forge-3.2.2.jar        |YUNG's Better Dungeons        |betterdungeons                |1.19.2-Forge-3.2.2  |DONE      |Manifest: NOSIGNATURE
		ftb-essentials-1902.1.10-build.47.jar             |FTB Essentials                |ftbessentials                 |1902.1.10-build.47  |DONE      |Manifest: NOSIGNATURE
		EasyAnvils-v4.0.8-1.19.2-Forge.jar                |Easy Anvils                   |easyanvils                    |4.0.8               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		YungsBetterWitchHuts-1.19.2-Forge-2.1.0.jar       |YUNG's Better Witch Huts      |betterwitchhuts               |1.19.2-Forge-2.1.0  |DONE      |Manifest: NOSIGNATURE
		scena-forge-1.0.93.jar                            |Scena                         |scena                         |1.0.93              |DONE      |Manifest: NOSIGNATURE
		player-animation-lib-forge-1.0.2.jar              |Player Animator               |playeranimator                |1.0.2               |DONE      |Manifest: NOSIGNATURE
		naturalist-forge-2.1.1-1.19.2.jar                 |Naturalist                    |naturalist                    |2.1.1               |DONE      |Manifest: NOSIGNATURE
		YungsBetterOceanMonuments-1.19.2-Forge-2.1.0.jar  |YUNG's Better Ocean Monuments |betteroceanmonuments          |1.19.2-Forge-2.1.0  |DONE      |Manifest: NOSIGNATURE
		HammerLib-1.19.2-19.3.56.jar                      |HammerLib                     |hammerlib                     |19.3.56             |DONE      |Manifest: 97:e8:52:e9:b3:f0:1b:83:57:4e:83:15:f7:e7:76:51:c6:60:5f:2b:45:59:19:a7:31:9e:98:69:56:4f:01:3c
		connectivity-1.19.2-3.4.jar                       |Connectivity Mod              |connectivity                  |1.19.2-3.4          |DONE      |Manifest: NOSIGNATURE
		mcw-windows-2.1.1-mc1.19.2forge.jar               |Macaw's Windows               |mcwwindows                    |2.1.1               |DONE      |Manifest: NOSIGNATURE
		sophisticatedcore-1.19.2-0.5.38.203.jar           |Sophisticated Core            |sophisticatedcore             |1.19.2-0.5.38.203   |DONE      |Manifest: NOSIGNATURE
		hourglass-1.19.1-1.2.1.1.jar                      |Hourglass                     |hourglass                     |1.19.1-1.2.1.1      |DONE      |Manifest: NOSIGNATURE
		mcwfurnituresbop-1.19.2-1.2.jar                   |Macaw's Furnitures - BOP      |mcwfurnituresbop              |1.19.2-1.2          |DONE      |Manifest: NOSIGNATURE
		XaerosWorldMap_1.29.2_Forge_1.19.1.jar            |Xaero's World Map             |xaeroworldmap                 |1.29.2              |DONE      |Manifest: NOSIGNATURE
		MoreMobGriefingOptions-1.19.2-2.0.3.jar           |More MobGriefing Options      |moremobgriefingoptions        |2.0.3               |DONE      |Manifest: NOSIGNATURE
		Controlling-forge-1.19.2-10.0+7.jar               |Controlling                   |controlling                   |10.0+7              |DONE      |Manifest: NOSIGNATURE
		Placebo-1.19.2-7.1.4.jar                          |Placebo                       |placebo                       |7.1.4               |DONE      |Manifest: NOSIGNATURE
		YungsApi-1.19.2-Forge-3.8.8.jar                   |YUNG's API                    |yungsapi                      |1.19.2-Forge-3.8.8  |DONE      |Manifest: NOSIGNATURE
		macawsbridgesbop-1.19.2-1.1.jar                   |Macaw's Bridges - BOP         |macawsbridgesbop              |1.19.2-1.1          |DONE      |Manifest: NOSIGNATURE
		Bookshelf-Forge-1.19.2-16.2.17.jar                |Bookshelf                     |bookshelf                     |16.2.17             |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		sophisticatedbackpacks-1.19.2-3.18.40.779.jar     |Sophisticated Backpacks       |sophisticatedbackpacks        |1.19.2-3.18.40.779  |DONE      |Manifest: NOSIGNATURE
		guardvillagers-1.19.2-1.5.2.jar                   |Guard Villagers               |guardvillagers                |1.19.2-1.5.2        |DONE      |Manifest: NOSIGNATURE
		mcw-doors-1.0.8forge-mc1.19.2.jar                 |Macaw's Doors                 |mcwdoors                      |1.0.8               |DONE      |Manifest: NOSIGNATURE
		jeed-1.19.2-1.18.jar                              |Just Enough Effect Description|jeed                          |1.19.2-1.18         |DONE      |Manifest: NOSIGNATURE
		TwerkItMeal-2.2.2.jar                             |TwerkItMeal                   |twerkitmeal                   |2.2.2               |DONE      |Manifest: NOSIGNATURE
		balm-forge-1.19.2-4.5.6.jar                       |Balm                          |balm                          |4.5.6               |DONE      |Manifest: NOSIGNATURE
		carryon-forge-1.19.2-2.0.5.10.jar                 |Carry On                      |carryon                       |2.0.5.10            |DONE      |Manifest: NOSIGNATURE
		JustEnoughResources-1.19.2-1.2.1.193.jar          |Just Enough Resources         |jeresources                   |1.2.1.193           |DONE      |Manifest: NOSIGNATURE
		BetterThanMending-1.7.2.jar                       |BetterThanMending             |betterthanmending             |1.7.2               |DONE      |Manifest: NOSIGNATURE
		FORGE-blanced_crates1.7.2-1.19.2.jar              |Balanced Crates               |balanced_crates               |1.7.2               |DONE      |Manifest: NOSIGNATURE
		YungsBetterNetherFortresses-1.19.2-Forge-1.0.5.jar|YUNG's Better Nether Fortresse|betterfortresses              |1.19.2-Forge-1.0.5  |DONE      |Manifest: NOSIGNATURE
		cloth-config-8.2.88-forge.jar                     |Cloth Config v8 API           |cloth_config                  |8.2.88              |DONE      |Manifest: NOSIGNATURE
		twilightforest-1.19.2-4.2.1518-universal.jar      |The Twilight Forest           |twilightforest                |4.2.1518            |DONE      |Manifest: NOSIGNATURE
		mob_grinding_utils-1.19.2-0.4.47.jar              |Mob Grinding Utils            |mob_grinding_utils            |1.19.2-0.4.47       |DONE      |Manifest: NOSIGNATURE
		refinedstorage-1.11.5.jar                         |Refined Storage               |refinedstorage                |1.11.5              |DONE      |Manifest: NOSIGNATURE
		easy_piglins-1.19.2-1.0.0.jar                     |Easy Piglins                  |easy_piglins                  |1.19.2-1.0.0        |DONE      |Manifest: NOSIGNATURE
		mcw-bridges-2.0.6-mc1.19.2forge.jar               |Macaw's Bridges               |mcwbridges                    |2.0.6               |DONE      |Manifest: NOSIGNATURE
		industrial-foregoing-1.19.2-3.3.2.2-4.jar         |Industrial Foregoing          |industrialforegoing           |3.3.2.2             |DONE      |Manifest: NOSIGNATURE
		FarmersDelight-1.19-1.2.0.jar                     |Farmer's Delight              |farmersdelight                |1.19-1.2.0          |DONE      |Manifest: NOSIGNATURE
		endsdelight-1.19.2-1.0.jar                        |End's Delight                 |ends_delight                  |1.19.2-1.0          |DONE      |Manifest: NOSIGNATURE
		LittleFrames_FORGE_v1.1.9_mc1.19.2.jar            |LittleFrames                  |littleframes                  |1.1.9               |DONE      |Manifest: NOSIGNATURE
		BotanyTrees-Forge-1.19.2-5.0.4.jar                |BotanyTrees                   |botanytrees                   |5.0.4               |DONE      |Manifest: NOSIGNATURE
		ToolStats-Forge-1.19.2-12.0.2.jar                 |ToolStats                     |toolstats                     |12.0.2              |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		material_elements_1.19.2-6.3.0.jar                |Material Elements             |material_elements             |6.3.0               |DONE      |Manifest: NOSIGNATURE
		Chunky-1.3.38.jar                                 |Chunky                        |chunky                        |1.3.38              |DONE      |Manifest: NOSIGNATURE
		mcw-trapdoors-1.0.8-mc1.19.2forge.jar             |Macaw's Trapdoors             |mcwtrpdoors                   |1.0.8               |DONE      |Manifest: NOSIGNATURE
		mcw-fences-1.0.7-mc1.19.2forge.jar                |Macaw's Fences and Walls      |mcwfences                     |1.0.7               |DONE      |Manifest: NOSIGNATURE
		easyhammers-1.19.2-4.0.0.jar                      |Easy Hammers                  |easyhammers                   |4.0.0               |DONE      |Manifest: NOSIGNATURE
		YungsBridges-1.19.2-Forge-3.1.0.jar               |YUNG's Bridges                |yungsbridges                  |1.19.2-Forge-3.1.0  |DONE      |Manifest: NOSIGNATURE
		Botania-1.19.2-438-FORGE.jar                      |Botania                       |botania                       |1.19.2-438-FORGE    |DONE      |Manifest: NOSIGNATURE
		DarkerDepths-1.19.2-1.0.0.jar                     |Darker Depths                 |darkerdepths                  |1.19-1.0.7          |DONE      |Manifest: NOSIGNATURE
		SolarFluxReborn-1.19.2-19.3.9.jar                 |Solar Flux Reborn             |solarflux                     |19.3.9              |DONE      |Manifest: 97:e8:52:e9:b3:f0:1b:83:57:4e:83:15:f7:e7:76:51:c6:60:5f:2b:45:59:19:a7:31:9e:98:69:56:4f:01:3c
		curios-forge-1.19.2-5.1.3.0.jar                   |Curios API                    |curios                        |1.19.2-5.1.3.0      |DONE      |Manifest: NOSIGNATURE
		Patchouli-1.19.2-77.jar                           |Patchouli                     |patchouli                     |1.19.2-77           |DONE      |Manifest: NOSIGNATURE
		blockui-1.19-0.0.64-ALPHA.jar                     |UI Library Mod                |blockui                       |1.19-0.0.64-ALPHA   |DONE      |Manifest: NOSIGNATURE
		OreExcavation-1.11.166.jar                        |OreExcavation                 |oreexcavation                 |1.11.166            |DONE      |Manifest: NOSIGNATURE
		YungsExtras-1.19.2-Forge-3.1.0.jar                |YUNG's Extras                 |yungsextras                   |1.19.2-Forge-3.1.0  |DONE      |Manifest: NOSIGNATURE
		elevatorid-1.19.2-1.8.9.jar                       |Elevator Mod                  |elevatorid                    |1.19.2-1.8.9        |DONE      |Manifest: NOSIGNATURE
		InfinityMending-1.19-0.2.0.jar                    |InfinityMending               |infinitymending               |0.2.0               |DONE      |Manifest: NOSIGNATURE
		YungsBetterStrongholds-1.19.2-Forge-3.2.0.jar     |YUNG's Better Strongholds     |betterstrongholds             |1.19.2-Forge-3.2.0  |DONE      |Manifest: NOSIGNATURE
		mcw-roofs-2.2.2-mc1.19.2forge.jar                 |Macaw's Roofs                 |mcwroofs                      |2.2.2               |DONE      |Manifest: NOSIGNATURE
		architectury-6.5.69-forge.jar                     |Architectury                  |architectury                  |6.5.69              |DONE      |Manifest: NOSIGNATURE
		identity-2.6.1-1.19.1-forge.jar                   |Identity                      |identity                      |2.6.1-1.19.1        |DONE      |Manifest: NOSIGNATURE
		cc-tweaked-1.19.2-1.101.2.jar                     |CC: Tweaked                   |computercraft                 |1.101.2             |DONE      |Manifest: NOSIGNATURE
		AI-Improvements-1.19.2-0.5.2.jar                  |AI-Improvements               |aiimprovements                |0.5.2               |DONE      |Manifest: NOSIGNATURE
		miners-lib-1.19.2-2.0.0.jar                       |Miner's Lib                   |miners_lib                    |2.0.0               |DONE      |Manifest: NOSIGNATURE
		mcw-furniture-3.1.0-mc1.19.2forge.jar             |Macaw's Furniture             |mcwfurnitures                 |3.1.0               |DONE      |Manifest: NOSIGNATURE
		foregoing_tweaker-1.19.2-1.1.5.jar                |Foregoing Tweaker             |foregoing_tweaker             |1.19.2-1.1.5        |DONE      |Manifest: NOSIGNATURE
		light-overlay-7.0.1-forge.jar                     |Light Overlay                 |lightoverlay                  |7.0.1               |DONE      |Manifest: NOSIGNATURE
		ItemPhysic_FORGE_v1.6.6_mc1.19.2.jar              |ItemPhysic                    |itemphysic                    |1.6.6               |DONE      |Manifest: NOSIGNATURE
		JadeAddons-1.19.2-forge-3.4.0.jar                 |Jade Addons                   |jadeaddons                    |3.4.0               |DONE      |Manifest: NOSIGNATURE
		FastLeafDecay-30.jar                              |FastLeafDecay                 |fastleafdecay                 |30                  |DONE      |Manifest: NOSIGNATURE
		CodeChickenLib-1.19.2-4.3.1.481-universal.jar     |CodeChicken Lib               |codechickenlib                |4.3.1.481           |DONE      |Manifest: 31:e6:db:63:47:4a:6e:e0:0a:2c:11:d1:76:db:4e:82:ff:56:2d:29:93:d2:e5:02:bd:d3:bd:9d:27:47:a5:71
		YungsBetterMineshafts-1.19.2-Forge-3.2.0.jar      |YUNG's Better Mineshafts      |bettermineshafts              |1.19.2-Forge-3.2.0  |DONE      |Manifest: NOSIGNATURE
		geckolib-forge-1.19-3.1.40.jar                    |GeckoLib                      |geckolib3                     |3.1.40              |DONE      |Manifest: NOSIGNATURE
		mcw-lights-1.0.5-mc1.19.2forge.jar                |Macaw's Lights and Lamps      |mcwlights                     |1.0.5               |DONE      |Manifest: NOSIGNATURE
		Cyclic-1.19.2-1.7.14.jar                          |Cyclic                        |cyclic                        |1.19.2-1.7.14       |DONE      |Manifest: 1f:47:ac:b1:61:82:96:b8:47:19:16:d2:61:81:11:60:3a:06:4b:61:31:56:7d:44:31:1e:0c:6f:22:5b:4c:ed
		crafting-on-a-stick-1.19.2-1.0.5.jar              |Crafting On A Stick           |crafting_on_a_stick           |1.0.5               |DONE      |Manifest: NOSIGNATURE
		easy_mob_farm_1.19.2-4.5.0.jar                    |Easy Mob Farm                 |easy_mob_farm                 |4.5.0               |DONE      |Manifest: NOSIGNATURE
		QuarkOddities-1.18.jar                            |Quark Oddities                |quarkoddities                 |1.18                |DONE      |Manifest: NOSIGNATURE
		trashslot-forge-1.19-12.0.2.jar                   |TrashSlot                     |trashslot                     |12.0.2              |DONE      |Manifest: NOSIGNATURE
		ftb-library-forge-1902.3.14-build.184.jar         |FTB Library                   |ftblibrary                    |1902.3.14-build.184 |DONE      |Manifest: NOSIGNATURE
		sophisticatedstorage-1.19.2-0.6.16.276.jar        |Sophisticated Storage         |sophisticatedstorage          |1.19.2-0.6.16.276   |DONE      |Manifest: NOSIGNATURE
		EasyMagic-v4.3.3-1.19.2-Forge.jar                 |Easy Magic                    |easymagic                     |4.3.3               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		jei-1.19.2-forge-11.6.0.1011.jar                  |Just Enough Items             |jei                           |11.6.0.1011         |DONE      |Manifest: NOSIGNATURE
		Pehkui-3.7.0+1.19.2-forge.jar                     |Pehkui                        |pehkui                        |3.7.0+1.19.2-forge  |DONE      |Manifest: NOSIGNATURE
		CuriosQuarkOBP-1.19.2-1.2.2.jar                   |Curios Quark Oddities Backpack|curiosquarkobp                |1.2.2               |DONE      |Manifest: NOSIGNATURE
		carpeted-1.19.2-1.4.jar                           |Carpeted                      |carpeted                      |1.19.2-1.4          |DONE      |Manifest: NOSIGNATURE
		waystones-forge-1.19.2-11.3.0.jar                 |Waystones                     |waystones                     |11.3.0              |DONE      |Manifest: NOSIGNATURE
		TaxFreeLevels-1.3.5-forge-1.19.jar                |Tax Free Levels               |taxfreelevels                 |1.3.5               |DONE      |Manifest: NOSIGNATURE
		mcw-paintings-1.0.4-mc1.19.2.jar                  |Macaw's Paintings             |mcwpaintings                  |1.0.4               |DONE      |Manifest: NOSIGNATURE
		Clumps-forge-1.19.2-9.0.0+14.jar                  |Clumps                        |clumps                        |9.0.0+14            |DONE      |Manifest: NOSIGNATURE
		shutupexperimentalsettings-1.0.5.jar              |Shutup Experimental Settings! |shutupexperimentalsettings    |1.0.5               |DONE      |Manifest: NOSIGNATURE
		NaturesCompass-1.19.2-1.10.0-forge.jar            |Nature's Compass              |naturescompass                |1.19.2-1.10.0-forge |DONE      |Manifest: NOSIGNATURE
		configured-2.0.1-1.19.2.jar                       |Configured                    |configured                    |2.0.1               |DONE      |Manifest: NOSIGNATURE
		CustomPlayerModels-1.19-0.6.5a.jar                |Customizable Player Models    |cpm                           |0.6.5a              |DONE      |Manifest: NOSIGNATURE
		compactmachines-5.1.0.jar                         |Compact Machines 5            |compactmachines               |5.1.0               |DONE      |Manifest: NOSIGNATURE
		Decorative Blocks-forge-1.19.2-3.0.0.jar          |Decorative Blocks             |decorative_blocks             |3.0.0               |DONE      |Manifest: NOSIGNATURE
		BotanyPots-Forge-1.19.2-9.0.27.jar                |BotanyPots                    |botanypots                    |9.0.27              |DONE      |Manifest: NOSIGNATURE
		snowundertrees-1.19.2-1.3.1.jar                   |Snow Under Trees              |snowundertrees                |1.3.1               |DONE      |Manifest: NOSIGNATURE
		mcjtylib-1.19-7.1.5.jar                           |McJtyLib                      |mcjtylib                      |1.19-7.1.5          |DONE      |Manifest: NOSIGNATURE
		rftoolsbase-1.19.1-4.1.5.jar                      |RFToolsBase                   |rftoolsbase                   |1.19.1-4.1.5        |DONE      |Manifest: NOSIGNATURE
		rftoolsstorage-1.19-4.1.0.jar                     |RFToolsStorage                |rftoolsstorage                |1.19-4.1.0          |DONE      |Manifest: NOSIGNATURE
		rftoolscontrol-1.19-6.1.2.jar                     |RFToolsControl                |rftoolscontrol                |1.19-6.1.2          |DONE      |Manifest: NOSIGNATURE
		rftoolsdim-1.19.2-9.1.2.jar                       |RFToolsDimensions             |rftoolsdim                    |1.19.2-9.1.2        |DONE      |Manifest: NOSIGNATURE
		YungsBetterDesertTemples-1.19.2-Forge-2.2.2.jar   |YUNG's Better Desert Temples  |betterdeserttemples           |1.19.2-Forge-2.2.2  |DONE      |Manifest: NOSIGNATURE
		trolldom-1.19.2-1.1.0.jar                         |Trolldom                      |trolldom                      |1.1.0               |DONE      |Manifest: NOSIGNATURE
		EnderStorage-1.19.2-2.10.1.181-universal.jar      |EnderStorage                  |enderstorage                  |2.10.1.181          |DONE      |Manifest: 31:e6:db:63:47:4a:6e:e0:0a:2c:11:d1:76:db:4e:82:ff:56:2d:29:93:d2:e5:02:bd:d3:bd:9d:27:47:a5:71
		CraftTweaker-forge-1.19.2-10.1.36.jar             |CraftTweaker                  |crafttweaker                  |10.1.36             |DONE      |Manifest: NOSIGNATURE
		Mekanism-1.19.2-10.3.8.477.jar                    |Mekanism                      |mekanism                      |10.3.8              |DONE      |Manifest: NOSIGNATURE
		MekanismGenerators-1.19.2-10.3.8.477.jar          |Mekanism: Generators          |mekanismgenerators            |10.3.8              |DONE      |Manifest: NOSIGNATURE
		MekanismAdditions-1.19.2-10.3.8.477.jar           |Mekanism: Additions           |mekanismadditions             |10.3.8              |DONE      |Manifest: NOSIGNATURE
		MekanismTools-1.19.2-10.3.8.477.jar               |Mekanism: Tools               |mekanismtools                 |10.3.8              |DONE      |Manifest: NOSIGNATURE
		rftoolspower-1.19-5.1.1.jar                       |RFToolsPower                  |rftoolspower                  |1.19-5.1.1          |DONE      |Manifest: NOSIGNATURE
		forge-1.19.2-43.2.4-universal.jar                 |Forge                         |forge                         |43.2.4              |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		mcw-paths-1.0.2forge-mc1.19.2.jar                 |Macaw's Paths and Pavings     |mcwpaths                      |1.0.2               |DONE      |Manifest: NOSIGNATURE
		craftingtweaks-forge-1.19-15.1.0.jar              |CraftingTweaks                |craftingtweaks                |15.1.0              |DONE      |Manifest: NOSIGNATURE
		server-1.19.2-20220805.130853-srg.jar             |Minecraft                     |minecraft                     |1.19.2              |DONE      |Manifest: NOSIGNATURE
		rftoolsutility-1.19-5.1.4.jar                     |RFToolsUtility                |rftoolsutility                |1.19-5.1.4          |DONE      |Manifest: NOSIGNATURE
		simplyswords-forge-1.36-1.19.2.jar                |Simply Swords                 |simplyswords                  |1.36-1.19.2         |DONE      |Manifest: NOSIGNATURE
		EnchantmentDescriptions-Forge-1.19.2-13.0.14.jar  |EnchantmentDescriptions       |enchdesc                      |13.0.14             |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		TerraBlender-forge-1.19.2-2.0.1.128.jar           |TerraBlender                  |terrablender                  |2.0.1.128           |DONE      |Manifest: NOSIGNATURE
		BiomesOPlenty-1.19.2-17.1.1.162.jar               |Biomes O' Plenty              |biomesoplenty                 |17.1.1.162          |DONE      |Manifest: NOSIGNATURE
		macawsroofsbop-1.19.2-1.3.jar                     |Macaw's Roofs - BOP           |macawsroofsbop                |1.19.2-1.3          |DONE      |Manifest: NOSIGNATURE
		mcwfencesbop-1.19.2-1.0.jar                       |Macaw's Fences - BOP          |mcwfencesbop                  |1.19.2-1.0          |DONE      |Manifest: NOSIGNATURE
		swingthroughgrass-1.19.2-1.10.0.jar               |SwingThroughGrass             |swingthroughgrass             |1.19.2-1.10.0       |DONE      |Manifest: NOSIGNATURE
		moonlight-1.19.2-2.2.15-forge.jar                 |Moonlight Library             |moonlight                     |1.19.2-2.2.15       |DONE      |Manifest: NOSIGNATURE
		smarterfarmers-1.19.2-1.7.1.jar                   |Smarter Farmers               |smarterfarmers                |1.19.2-1.7.1        |DONE      |Manifest: NOSIGNATURE
		bettercombat-forge-1.5.5+1.19.jar                 |Better Combat                 |bettercombat                  |1.5.5+1.19          |DONE      |Manifest: NOSIGNATURE
		titanium-1.19.2-3.7.2-26.jar                      |Titanium                      |titanium                      |3.7.2               |DONE      |Manifest: NOSIGNATURE
		EnigmaticGraves-1.19.2-1.7.6.jar                  |Enigmatic Graves              |enigmaticgraves               |1.19.2-1.7.6        |DONE      |Manifest: NOSIGNATURE
		Jade-1.19.1-forge-8.8.0.jar                       |Jade                          |jade                          |8.8.0               |DONE      |Manifest: NOSIGNATURE
		appliedenergistics2-forge-12.9.2.jar              |Applied Energistics 2         |ae2                           |12.9.2              |DONE      |Manifest: NOSIGNATURE
		AE2WTLib-12.8.5.jar                               |AE2WTLib                      |ae2wtlib                      |12.8.5              |DONE      |Manifest: NOSIGNATURE
		BuildingWands_mc1.19.2-2.6.4_release-forge.jar    |Building Wands                |wands                         |2.6.4_release       |DONE      |Manifest: NOSIGNATURE
		CreativeCore_FORGE_v2.9.3_mc1.19.2.jar            |CreativeCore                  |creativecore                  |2.9.3               |DONE      |Manifest: NOSIGNATURE
		spectrelib-forge-0.11.0+1.19.jar                  |SpectreLib                    |spectrelib                    |0.11.0+1.19         |DONE      |Manifest: NOSIGNATURE
		NethersDelight-1.19-3.0.jar                       |Nether's Delight              |nethersdelight                |1.19-3.0            |DONE      |Manifest: NOSIGNATURE
		Ding-1.19.2-Forge-1.4.0.jar                       |Ding                          |ding                          |1.4.0               |DONE      |Manifest: NOSIGNATURE
		domum_ornamentum-1.19-1.0.76-ALPHA-universal.jar  |Domum Ornamentum              |domum_ornamentum              |1.19-1.0.76-ALPHA   |DONE      |Manifest: NOSIGNATURE
		rftoolsbuilder-1.19.1-5.2.3.jar                   |RFToolsBuilder                |rftoolsbuilder                |1.19.1-5.2.3        |DONE      |Manifest: NOSIGNATURE
		easy_villagers-1.19.2-1.0.0.jar                   |Easy Villagers                |easy_villagers                |1.19.2-1.0.0        |DONE      |Manifest: NOSIGNATURE
		flywheel-forge-1.19.2-0.6.8.a-14.jar              |Flywheel                      |flywheel                      |0.6.8.a-14          |DONE      |Manifest: NOSIGNATURE
		create-1.19.2-0.5.0.i.jar                         |Create                        |create                        |0.5.0.i             |DONE      |Manifest: NOSIGNATURE
		mutil-1.19.2-5.1.0.jar                            |mutil                         |mutil                         |5.1.0               |DONE      |Manifest: NOSIGNATURE
		Xaeros_Minimap_23.2.0_Forge_1.19.1.jar            |Xaero's Minimap               |xaerominimap                  |23.2.0              |DONE      |Manifest: NOSIGNATURE
		easy_hammers_plus-1.19.2-1.0.1.jar                |Easy Hammers Plus             |easy_hammers_plus             |1.0.1               |DONE      |Manifest: NOSIGNATURE
		FastWorkbench-1.19.2-7.0.1.jar                    |Fast Workbench                |fastbench                     |7.0.1               |DONE      |Manifest: NOSIGNATURE
		polymorph-forge-0.46.1+1.19.2.jar                 |Polymorph                     |polymorph                     |0.46.1+1.19.2       |DONE      |Manifest: NOSIGNATURE
		JustEnoughProfessions-forge-1.19.2-2.0.2.jar      |Just Enough Professions (JEP) |justenoughprofessions         |2.0.2               |DONE      |Manifest: NOSIGNATURE
		AutoRegLib-1.8.2-55.jar                           |AutoRegLib                    |autoreglib                    |1.8.2-55            |DONE      |Manifest: NOSIGNATURE
		Quark-3.4-394.jar                                 |Quark                         |quark                         |3.4-394             |DONE      |Manifest: NOSIGNATURE
		StorageDrawers-1.19-11.1.2.jar                    |Storage Drawers               |storagedrawers                |11.1.2              |DONE      |Manifest: NOSIGNATURE
		FluxNetworks-1.19.2-7.1.3.12.jar                  |Flux Networks                 |fluxnetworks                  |7.1.3.12            |DONE      |Manifest: NOSIGNATURE
		entityculling-forge-1.6.1-mc1.19.2.jar            |EntityCulling                 |entityculling                 |1.6.1               |DONE      |Manifest: NOSIGNATURE
		structurize-1.19.2-1.0.483-ALPHA.jar              |Structurize                   |structurize                   |1.19.2-1.0.483-ALPHA|DONE      |Manifest: NOSIGNATURE
		multipiston-1.19.2-1.2.21-ALPHA.jar               |Multi-Piston                  |multipiston                   |1.19.2-1.2.21-ALPHA |DONE      |Manifest: NOSIGNATURE
		minecolonies-1.19.2-1.0.1273-ALPHA.jar            |MineColonies                  |minecolonies                  |1.19.2-1.0.1273-ALPH|DONE      |Manifest: NOSIGNATURE
		appleskin-forge-mc1.19-2.4.2.jar                  |AppleSkin                     |appleskin                     |2.4.2+mc1.19        |DONE      |Manifest: NOSIGNATURE
		moredragoneggs-3.2.jar                            |More Dragon Eggs              |moredragoneggs                |3.2                 |DONE      |Manifest: NOSIGNATURE
		PuzzlesLib-v4.3.12-1.19.2-Forge.jar               |Puzzles Lib                   |puzzleslib                    |4.3.12              |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		BetterF3-4.0.0-Forge-1.19.2.jar                   |BetterF3                      |betterf3                      |4.0.0               |DONE      |Manifest: NOSIGNATURE
		cave-enhancements-1.19.2-2.1.11-forge.jar         |Cave Enhancements             |cave_enhancements             |1.19.2-2.1.11-forge |DONE      |Manifest: NOSIGNATURE
		refinedstorageaddons-0.9.0.jar                    |Refined Storage Addons        |refinedstorageaddons          |0.9.0               |DONE      |Manifest: NOSIGNATURE
		Applied-Mekanistics-1.3.4.jar                     |Applied Mekanistics           |appmek                        |1.3.4               |DONE      |Manifest: NOSIGNATURE
		CosmeticArmorReworked-1.19.2-v1a.jar              |CosmeticArmorReworked         |cosmeticarmorreworked         |1.19.2-v1a          |DONE      |Manifest: 5e:ed:25:99:e4:44:14:c0:dd:89:c1:a9:4c:10:b5:0d:e4:b1:52:50:45:82:13:d8:d0:32:89:67:56:57:01:53
		chisels-and-bits-forge-1.3.129.jar                |chisels-and-bits              |chiselsandbits                |1.3.129             |DONE      |Manifest: NOSIGNATURE

	FML: 43.2
	Forge: net.minecraftforge:43.2.4

**Comment by McJty** [comment]
The RFToolsUtility clock module sync all the time. It uses level.getGameTime() on the client. The hourglass mod is supposed to update that. It's their bug
