### ISSUE TITLE
RfTools has failed, help me

### ISSUE THREAD

**Issue by eoarthurnepai** [McJtyMods/RFToolsUtility#173]
[latest.log](https://github.com/McJtyMods/RFToolsUtility/files/11107182/latest.log)
![screen](https://user-images.githubusercontent.com/129351205/228713492-4540b72c-0e92-4479-a429-7b5bddecf2be.png)
[crash-2023-03-29_23.26.06-fml.txt](https://github.com/McJtyMods/RFToolsUtility/files/11107183/crash-2023-03-29_23.26.06-fml.txt)

**Comment by McJty** [comment]
Update the mods. You are using versions that are too old. For example, rftoolsbase is now 4.1.6
