### ISSUE TITLE
No screens GUI in server

### ISSUE THREAD

**Issue by Werewolf-p** [McJtyMods/RFToolsUtility#176]
If i try to use the GUI from the screens in the server it does not show a GUI, it does work in singleplayer.
used both sneak right click and not sneaking , with and without items in hand
rftoolsbase-1.16-2.1.5
rftoolsutility-1.16-3.1.16

**Comment by McJty** [comment]
What exactly are you doing? You have both hands empty?

**Comment by Werewolf-p** [comment]
ow apparently you can't have a shield equiped sorry for the inconfidence :D
