### ISSUE TITLE
Clear button in Inventory Checker's tag dialogue doesn't clear the tag, but effectively is the same as Close

### ISSUE THREAD

**Issue by Jack-McKalling** [McJtyMods/RFToolsUtility#178]
If you open an Inventory Checker, and set a tag for it but now want to clear it, you can't.

**How to reproduce:**

1. Place down an Inventory Checker
2. Open its GUI and click the Tag control
3. Click on the first listed tag and then on the Close button
    ✔️ The Tag control now displays the selected tag
4. Click on the Tag control again, and click the Clear button
    ❌ The Tag control still displays the previously selected tag

**Versions:**
MC: 1.19.3
Forge: 1.19.3-44.1.23
RFTools:
- mcjtylib: 1.19.3-7.2.4
- rftoolsbase: 1.19-4.1.7
- rftoolsutility: 1.19-5.1.6

**Comment by McJty** [comment]
Fixed in next version of rftools utility
