### ISSUE TITLE
Game crashes upon clicking the space below the last tag in Inventory Checker, in its tag dialogue

### ISSUE THREAD

**Issue by Jack-McKalling** [McJtyMods/RFToolsUtility#179]
There is a narrow space below the lowest tag, in the Tag dialogue that opens if you click on the Tag control in the Inventory Checker.
If you click said space, the game crashes, since it tries to interpret a list index there that obviously doesn't exist.

**How to reproduce:**
1. Place down an Inventory Checker
2. Right-click it to open the GUI
3. Click on the Tag control to open the dialogue
4. Click on a tag and hit the Close button
5. Repeat step 3
6. Click on the narrow area below the last tag in the list
    ❌ crash

**Reasoning for doing this:**
Due to the issue described in #178, the Clear button doesn't function, I tried to "select" outside of the options instead, to see if that could select nothing for clearing the previously selected tag.

**Expected behaviour:**
It should not be possible to click on the area below the last tag in the list, nothing should happen when you do. But instead the Clear button should be what removes the selection. And the click-event should be suppressed on the areas outside the list options.

**Crash log:**
https://gist.github.com/Jack-McKalling/db0f7c59d8e548242d26ba642dd28eb2

**Comment by McJty** [comment]
I will check it out

**Comment by McJty** [comment]
Fixed in the next version of McJtyLib
