### ISSUE TITLE
[1.19.4] Displaced, Red Remembered Crafting Inputs in the Crafter

### ISSUE THREAD

**Issue by HalcyonSeas73** [McJtyMods/RFToolsUtility#181]
Forge: 45.0.63
McJtyLib: 7.2.6
RFToolsBase: 4.1.7
RFToolsUtility: 5.1.7

Found a maybe-bug; when remembering an item in the Crafter slot, it becomes red, and is also off-centre for the window scale. I only say maybe-bug since it could very well be a mod conflict somehow doing it.
![image](https://github.com/McJtyMods/RFToolsUtility/assets/84727791/684b925f-983f-4055-ae01-1a124d513fec)
![image](https://github.com/McJtyMods/RFToolsUtility/assets/84727791/3aa665b4-05e5-46ee-af56-82bbb7fa5f6b)

**Comment by InfinityGaben** [comment]
I've also noticed this issue with the 1.20 version, the icons are all the way in the bottom right when it is remembering slots. at first should it was a issue with my shaders so i disabled them, and still had it so was looking for reports on it, im shocked that this has been happening since 1.19.

**Comment by McJty** [comment]
I'll check it out

**Comment by McJty** [comment]
Fixed next release for 1.20.1
