### ISSUE TITLE
[1.19.2] Screen controller doesn't connect to any screens

### ISSUE THREAD

**Issue by a-usr** [McJtyMods/RFToolsUtility#183]
The screen controller is actively being powered and the screen that is to be controlled is mounted on the screen controller's front.

**Comment by McJty** [comment]
That's not needed. It can be at a distance. Did you press the 'scan' button on the controller GUI? Can you show a screenshot?

**Comment by a-usr** [comment]
The controller doesnt connect to the screen regardless of the distance, even after repeatedly pressing 'scan'. Also it isnt just a problem with the screen not showing up in the controller's GUI, as the Screen doesnt get any power even though the controller is completely charged and connected to an active energy source (ae2's Energy.Gen or FE.Gen or something like that. The controller is pulling power from it). As for a Screenshot, im too lazy to spin up minecraft rn.

**Comment by McJty** [comment]
Well give me a screenshot whenever you can

**Comment by McJty** [comment]
Works for me
