### ISSUE TITLE
Syringe Crafting

### ISSUE THREAD

**Issue by DinnerBeef** [McJtyMods/RFToolsUtility#185]
When you craft a syringe, you craft a level 100 and not a level 0 one.

![image](https://github.com/McJtyMods/RFToolsUtility/assets/8346986/827c9639-34c3-418a-a72f-d61a2f3c9463)

Minecraft Version: 1.20.1
Forge Version: 47.1.28
Mod Version: rftoolsutility-1.20-6.0.0.jar

**Comment by McJty** [comment]
Will be fixed next release. Note that it's only a visual bug. It's actually ok to use
