### ISSUE TITLE
1.20.1 SCREEN Not working

### ISSUE THREAD

**Issue by MUHAKLorTheDorfTrottel4Github** [McJtyMods/RFToolsUtility#188]
1.20.1-forge-47.1.44
mcjtylib-1.20-8.0.2
rftoolsutility-1.20-6.0.1
rftoolsbase-1.20-5.0.1
xnet-1.20-6.0.1

Hi Jorrit 
following behavour:
Scan Controller well powered via xnet
placed a screen next to it >SCAN , no success 
click on screen no GUI

btw
Xnet working flawless with 20 Adv.connectors, Power, Item and Juice networks

daniel
greeting from Munich

**Comment by McJty** [comment]
Can you show me some screenshots?

**Comment by MUHAKLorTheDorfTrottel4Github** [comment]
![2023-08-24_13 48 48](https://github.com/McJtyMods/RFToolsUtility/assets/18631808/bfdbecc0-10e1-49cf-a778-39da152b22a9)

press >scan<  nothing happens
( i did a lot screens in the past )

**Comment by McJty** [comment]
Well you need to insert modules in the screen

**Comment by MUHAKLorTheDorfTrottel4Github** [comment]
ok, energy module radinf dimcell shows "numbers"
text module can be inseted ( clicked ), but HOW to edit test
click on screen nothing happen
wrench do the job on screen like it should 
SCAN on controller no reacion , but screen seems powered

**Comment by MUHAKLorTheDorfTrottel4Github** [comment]
my xnet
[xnet.pdf](https://github.com/McJtyMods/RFToolsUtility/files/12429411/xnet.pdf)
tip: NAME the chanels, later no info which is what

**Comment by McJty** [comment]
Sneak right click with empty hand to open the screen gui so you can edit the text

**Comment by MUHAKLorTheDorfTrottel4Github** [comment]
my sneak is RIGHT SHIFT, no double assingment
empty hand, sneak right click does not open gui

i may tomorrow set up a creative world with only your mods,
to ensure that no other mod claiming something

**Comment by MUHAKLorTheDorfTrottel4Github** [comment]
good for you, bad for me
in a creative test world with only all your 7 mods:

Everything works like it should (except ScreenContoller has no status)
SNEAK+R.CLICK opens screen menu

Now the hassle begins for me

**Comment by MUHAKLorTheDorfTrottel4Github** [comment]
Problem solved:
the OFFHAND must be EMPTY, even with shield no GUI
no shield>gui , shield >no gui
as far as i remember, it was not like this in 1.19.x
