### ISSUE TITLE
Screen Controller, Teleporter Probe, Simple Dialer missing localization

### ISSUE THREAD

**Issue by Smollet777** [McJtyMods/RFToolsUtility#19]
![image](https://user-images.githubusercontent.com/41921653/75662807-66474880-5c78-11ea-8c20-239c63d97530.png)

mcjtylib-1.14-3.5.17-alpha
rftoolsbase-1.14-0.0.12-alpha
rftoolsutility-1.14-1.2.14-alpha

**Comment by McJty** [comment]
I no longer develop on 1.14
