### ISSUE TITLE
[1.20.1]The energy reading limit of energy module

### ISSUE THREAD

**Issue by Cronos27X** [McJtyMods/RFToolsUtility#199]
The energy module have a energy reading limit that the maximum is 2^31 which is not enough for some large-capacity energy storage device like Mekanism. When I try to monitor the induction matrix which have 1.0T/1.6T FE the energy module says it just have 2.1G FE and 100% of usage rate. Please fix it.

**Comment by McJty** [comment]
Forge Energy only allows for 2^31. Anything higher is not supported by Forge Energy and is custom to that mod. It's not easy for me to handle all mod specific huge energy sources so this is generally something that I don't fix

**Comment by deNStep123** [comment]
> Forge Energy only allows for 2^31. Anything higher is not supported by Forge Energy and is custom to that mod. It's not easy for me to handle all mod specific huge energy sources so this is generally something that I don't fix

could i do this by myself? like change some configs only for my game

**Comment by McJty** [comment]
It's not a config matter. It's a fundamental thing that can only be fixed in the mod itself
