### ISSUE TITLE
[1.15.2] Server crash on startup

### ISSUE THREAD

**Issue by ocram9** [McJtyMods/RFToolsUtility#23]
When starting the server it crashes after the world is loaded. Downgrading to 2.0.1 fixes this issue.

### Versions:
- Minecraft 1.15.2
- Forge 31.1.77
- RfToolsUtility 2.1.1-beta

### Logs:
- Crash Log: https://gist.github.com/ocram9/f852b0b837a0d1316af82d1c223c692d
- Latest Log: https://gist.github.com/ocram9/57f37087ff315629f51813efda6e65b6

**Comment by McJty** [comment]
Can you tell me what recipes you have in that crafter?

**Comment by ocram9** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/49008532/81550627-d3fea780-9380-11ea-8cc7-a8272f1742ff.png)

These are all mystical agriculture recipes. The crystal in the middle can be re-used infinite amount of times. Also, as a side note, the crash log says it's that crafter but the coords don't match up. These coords are pointing to a cable from refined storage that is behind the crafter.

**Comment by ocram9** [comment]
Correction: It's actually an importer from refined storage.

**Comment by McJty** [comment]
Will be fixed in the next release
