### ISSUE TITLE
1.15.2 Crafter crash

### ISSUE THREAD

**Issue by Knito58** [McJtyMods/RFToolsUtility#24]
Description: Ticking entity
java.lang.IndexOutOfBoundsException: Index: 3, Size: 3
https://pastebin.com/HZDT2KAH

In a tier1 and tier3 crafter I try to make netherstars from mystical agradditions.
The 1st recipe is 9x netherstar essence to make 1 nether star shard. Set to intern, keep or all => works.

When the shard is arrived in the internal inventory of the crafter I try to set up the second recipe:
3 x shard => shows the correct netherstar icon as result, "all" or "keep", extern.
Click Apply => crash.

I tried several times with blocking empty slots w cobble or using "keep" instead of "all" and tried tier1 and tier3 crafters. The result was always this crash. Crafting a nether star "by hand" in the player's inv works without crashing the game. (test if mystical aggr works as it seems to be suspicious, too)

I have 

optifine preview,
Forge 31.1.74
rftoolsutility-1.15-2.1.1-beta
mcjtylib-1.15-4.1.0-beta

**Comment by McJty** [comment]
Will be fixed in the next release

**Comment by Knito58** [comment]
Fix confirmed!
Thank you very much.
