### ISSUE TITLE
Inventory tweaks can sort items into crafter ghostslots

### ISSUE THREAD

**Issue by Darkere** [McJtyMods/RFToolsUtility#26]
Inventory tweaks can currently sort the inventory of a crafter. In which case items from the players inventory end up in the grid (effectively voiding them).

I recently fixed this for RS by overriding `canTake()` for slots that players are not supposed to be able to insert/extract items. 
Not certain that completely fixes it. but should help.

**Comment by McJty** [comment]
But what slots should the player not be able to extract items from? That doesn't make sense. All slots of the crafter should return true for canTake

**Comment by Darkere** [comment]
Ah I meant the crafting grid. Players should not be able to extract real items from the crafting grid. 

I'll test it out and PR :)

**Comment by Darkere** [comment]
Ok i'm a derp. 

You are already overriding `canTakeStack` for the crafting grid slots. 

This means Inventory tweaks is not able to extract items from the slots. It is still able to insert into them. 

Not sure what can be done to avoid this https://gfycat.com/BelatedTinyAmericanbobtail then. I've blacklisted the inventory for my pack but I imagine other people will still run into it.

**Comment by Darkere** [comment]
This was fixed by Inventory Tweaks.
