### ISSUE TITLE
[1.16.2] Syrige over lapping in creative mode

### ISSUE THREAD

**Issue by BedrockLegends** [McJtyMods/RFToolsUtility#29]
![2020-08-20_13 30 58](https://user-images.githubusercontent.com/48525410/90811019-8253aa80-e2e9-11ea-99b9-66a09f11afa0.png)

**Comment by thevortex** [comment]
seeing this on many creative tabs as well, full of 100 level pig syringes, and one level 0 empty syringe.

**Comment by McJty** [comment]
Was fixed some time ago
