### ISSUE TITLE
Crash on startup [1.14.4]

### ISSUE THREAD

**Issue by MelanX** [McJtyMods/RFToolsUtility#3]
Forge: 28.1.70
RFTools Utility: 1.2.6-alpha
Crash-log: https://pastebin.com/yqjNCJtx

Whether with or without OptiFine.
Do you need more information? Tell me, please :)

(should be same bug like [here](https://github.com/McJtyMods/RFToolsPower/issues/32))

**Comment by McJty** [comment]
Bug in forge. Just start again
