### ISSUE TITLE
1.15.2 syringe everywhere in creative

### ISSUE THREAD

**Issue by Shucre** [McJtyMods/RFToolsUtility#30]
So the syringes appear in every tabs, i don't know why or how.
![Capture](https://user-images.githubusercontent.com/53821065/90956797-02b11180-e48a-11ea-8127-984234f803f1.JPG)
Hope my report can help you.

**Comment by seancrain** [comment]
This issue is present in 1.16 as well

**Comment by McJty** [comment]
Was fixed some time ago
