### ISSUE TITLE
[1.16.2] Server crash

### ISSUE THREAD

**Issue by BedrockLegends** [McJtyMods/RFToolsUtility#31]
24.08 11:07:23 [Server] main/FATAL [ne.mi.fm.lo.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/world/ClientWorld for invalid dist DEDICATED_SERVER
24.08 11:07:23 [Server] main/ERROR [ne.mi.fm.ja.FMLModContainer/]: Exception caught during firing event: Attempted to load class net/minecraft/client/world/ClientWorld for invalid dist DEDICATED_SERVER
24.08 11:07:23 [Server] INFO Index: 2
24.08 11:07:23 [Server] INFO Listeners:
24.08 11:07:23 [Server] INFO 0: NORMAL
24.08 11:07:23 [Server] INFO 1: ASM: net.minecraftforge.registries.DeferredRegister$EventDispatcher@7cdf52a3 handleEvent(Lnet/minecraftforge/event/RegistryEvent$Register;)V
24.08 11:07:23 [Server] INFO 2: ASM: net.minecraftforge.registries.DeferredRegister$EventDispatcher@cd1a1a8 handleEvent(Lnet/minecraftforge/event/RegistryEvent$Register;)V
24.08 11:07:23 [Server] INFO 3: ASM: net.minecraftforge.registries.DeferredRegister$EventDispatcher@116dc09 handleEvent(Lnet/minecraftforge/event/RegistryEvent$Register;)V
24.08 11:07:23 [Server] INFO 4: ASM: net.minecraftforge.registries.DeferredRegister$EventDispatcher@1adf5883 handleEvent(Lnet/minecraftforge/event/RegistryEvent$Register;)V
24.08 11:07:23 [Server] INFO 5: ASM: net.minecraftforge.registries.DeferredRegister$EventDispatcher@1c935b31 handleEvent(Lnet/minecraftforge/event/RegistryEvent$Register;)V
24.08 11:07:23 [Server] INFO 6: ASM: net.minecraftforge.registries.DeferredRegister$EventDispatcher@1dce65ea handleEvent(Lnet/minecraftforge/event/RegistryEvent$Register;)V
24.08 11:07:23 [Server] INFO 7: ASM: class mcjty.rftoolsutility.setup.Registration registerSounds(Lnet/minecraftforge/event/RegistryEvent$Register;)V
24.08 11:07:23 [Server] INFO java.lang.RuntimeException: Attempted to load class net/minecraft/client/world/ClientWorld for invalid dist DEDICATED_SERVER
24.08 11:07:23 [Server] INFO at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:71)
24.08 11:07:23 [Server] INFO at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:82)
24.08 11:07:23 [Server] INFO at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:118)
24.08 11:07:23 [Server] INFO at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:247)
24.08 11:07:23 [Server] INFO at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:134)
24.08 11:07:23 [Server] INFO at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:96)
24.08 11:07:23 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
24.08 11:07:23 [Server] INFO at mcjty.rftoolsutility.modules.teleporter.items.porter.ChargedPorterItem.initOverrides(ChargedPorterItem.java:137)
24.08 11:07:23 [Server] INFO at mcjty.rftoolsutility.modules.teleporter.items.porter.ChargedPorterItem.<init>(ChargedPorterItem.java:85)
24.08 11:07:23 [Server] INFO at mcjty.rftoolsutility.modules.teleporter.items.porter.ChargedPorterItem.<init>(ChargedPorterItem.java:75)
24.08 11:07:23 [Server] INFO at net.minecraftforge.registries.DeferredRegister.lambda$register$0(DeferredRegister.java:124)
24.08 11:07:23 [Server] INFO at net.minecraftforge.registries.DeferredRegister.addEntries(DeferredRegister.java:200)
24.08 11:07:23 [Server] INFO at net.minecraftforge.registries.DeferredRegister.access$000(DeferredRegister.java:61)
24.08 11:07:23 [Server] INFO at net.minecraftforge.registries.DeferredRegister$EventDispatcher.handleEvent(DeferredRegister.java:172)
24.08 11:07:23 [Server] INFO at net.minecraftforge.eventbus.ASMEventHandler_10_EventDispatcher_handleEvent_Register.invoke(.dynamic)
24.08 11:07:23 [Server] INFO at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
24.08 11:07:23 [Server] INFO at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297)
24.08 11:07:23 [Server] INFO at net.minecraftforge.fml.javafmlmod.FMLModContainer.fireEvent(FMLModContainer.java:110)
24.08 11:07:23 [Server] INFO at net.minecraftforge.fml.javafmlmod.FMLModContainer$ErroringConsumer.accept(FMLModContainer.java:190)
24.08 11:07:23 [Server] INFO at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:113)
24.08 11:07:23 [Server] INFO at net.minecraftforge.fml.ModList.lambda$dispatchSynchronousEvent$5(ModList.java:126)
24.08 11:07:23 [Server] INFO at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
24.08 11:07:23 [Server] INFO at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
24.08 11:07:23 [Server] INFO at net.minecraftforge.fml.ModList.dispatchSynchronousEvent(ModList.java:126)
24.08 11:07:23 [Server] INFO at net.minecraftforge.fml.ModList.lambda$static$1(ModList.java:96)
24.08 11:07:23 [Server] INFO at net.minecraftforge.fml.LifecycleEventProvider.dispatch(LifecycleEventProvider.java:71)
24.08 11:07:23 [Server] INFO at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:214)
24.08 11:07:23 [Server] INFO at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$25(ModLoader.java:206)
24.08 11:07:23 [Server] INFO at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:826)
24.08 11:07:23 [Server] INFO at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:206)
24.08 11:07:23 [Server] INFO at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:49)
24.08 11:07:23 [Server] INFO at net.minecraft.server.Main.main(Main.java:96)
24.08 11:07:23 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
24.08 11:07:23 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
24.08 11:07:23 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
24.08 11:07:23 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498)
24.08 11:07:23 [Server] INFO at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51)
24.08 11:07:23 [Server] INFO at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
24.08 11:07:23 [Server] INFO at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
24.08 11:07:23 [Server] INFO at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
24.08 11:07:23 [Server] INFO at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
24.08 11:07:23 [Server] INFO at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)
24.08 11:07:23 [Server] INFO at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63)
24.08 11:07:23 [Server] INFO at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60)
24.08 11:07:23 [Server] INFO at net.minecraftforge.server.ServerMain.main(ServerMain.java:57)
24.08 11:07:23 [Server] main/ERROR [ne.mi.fm.ja.FMLModContainer/LOADING]: Caught exception during event RegistryEvent.Register<minecraft:item> dispatch for modid rftoolsutility
24.08 11:07:23 [Server] INFO java.lang.RuntimeException: Attempted to load class net/minecraft/client/world/ClientWorld for invalid dist DEDICATED_SERVER
24.08 11:07:23 [Server] INFO at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:71) ~[forge-1.16.2-33.0.20.jar:33.0] {}
24.08 11:07:23 [Server] INFO at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:82) ~[modlauncher-6.1.1.jar:?] {}
24.08 11:07:23 [Server] INFO at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:118) ~[modlauncher-6.1.1.jar:?] {}
24.08 11:07:23 [Server] INFO at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:247) ~[modlauncher-6.1.1.jar:?] {}
24.08 11:07:23 [Server] INFO at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:134) ~[modlauncher-6.1.1.jar:?] {re:classloading}
24.08 11:07:23 [Server] INFO at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:96) ~[modlauncher-6.1.1.jar:?] {re:classloading}
24.08 11:07:23 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_251] {}
24.08 11:07:23 [Server] INFO at mcjty.rftoolsutility.modules.teleporter.items.porter.ChargedPorterItem.initOverrides(ChargedPorterItem.java:137) ~[?:1.16-3.0.2] {re:classloading}
24.08 11:07:23 [Server] INFO at mcjty.rftoolsutility.modules.teleporter.items.porter.ChargedPorterItem.<init>(ChargedPorterItem.java:85) ~[?:1.16-3.0.2] {re:classloading}
24.08 11:07:23 [Server] INFO at mcjty.rftoolsutility.modules.teleporter.items.porter.ChargedPorterItem.<init>(ChargedPorterItem.java:75) ~[?:1.16-3.0.2] {re:classloading}
24.08 11:07:23 [Server] INFO at net.minecraftforge.registries.DeferredRegister.lambda$register$0(DeferredRegister.java:124) ~[?:?] {re:classloading}
24.08 11:07:23 [Server] INFO at net.minecraftforge.registries.DeferredRegister.addEntries(DeferredRegister.java:200) ~[?:?] {re:classloading}
24.08 11:07:23 [Server] INFO at net.minecraftforge.registries.DeferredRegister.access$000(DeferredRegister.java:61) ~[?:?] {re:classloading}
24.08 11:07:23 [Server] INFO at net.minecraftforge.registries.DeferredRegister$EventDispatcher.handleEvent(DeferredRegister.java:172) ~[?:?] {re:classloading}
24.08 11:07:23 [Server] INFO at net.minecraftforge.eventbus.ASMEventHandler_10_EventDispatcher_handleEvent_Register.invoke(.dynamic) ~[?:?] {}
24.08 11:07:23 [Server] INFO at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.3-service.jar:?] {}
24.08 11:07:23 [Server] INFO at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.3-service.jar:?] {}
24.08 11:07:23 [Server] INFO at net.minecraftforge.fml.javafmlmod.FMLModContainer.fireEvent(FMLModContainer.java:110) ~[?:33.0] {re:classloading}
24.08 11:07:23 [Server] INFO at net.minecraftforge.fml.javafmlmod.FMLModContainer$ErroringConsumer.accept(FMLModContainer.java:190) ~[?:33.0] {re:classloading}
24.08 11:07:23 [Server] INFO at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:113) ~[?:?] {re:classloading}
24.08 11:07:23 [Server] INFO at net.minecraftforge.fml.ModList.lambda$dispatchSynchronousEvent$5(ModList.java:126) ~[?:?] {re:classloading}
24.08 11:07:23 [Server] INFO at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[?:1.8.0_251] {}
24.08 11:07:23 [Server] INFO at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580) ~[?:1.8.0_251] {}
24.08 11:07:23 [Server] INFO at net.minecraftforge.fml.ModList.dispatchSynchronousEvent(ModList.java:126) ~[?:?] {re:classloading}
24.08 11:07:23 [Server] INFO at net.minecraftforge.fml.ModList.lambda$static$1(ModList.java:96) ~[?:?] {re:classloading}
24.08 11:07:23 [Server] INFO at net.minecraftforge.fml.LifecycleEventProvider.dispatch(LifecycleEventProvider.java:71) ~[?:?] {re:classloading}
24.08 11:07:23 [Server] INFO at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:214) ~[?:?] {re:classloading}
24.08 11:07:23 [Server] INFO at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$25(ModLoader.java:206) ~[?:?] {re:classloading}
24.08 11:07:23 [Server] INFO at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:826) ~[?:?] {re:classloading}
24.08 11:07:23 [Server] INFO at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:206) ~[?:?] {re:classloading}
24.08 11:07:23 [Server] INFO at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:49) ~[?:?] {re:classloading}
24.08 11:07:23 [Server] INFO at net.minecraft.server.Main.main(Main.java:96) ~[?:?] {re:classloading}
24.08 11:07:23 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_251] {}

Pretty much the same one from here https://github.com/McJtyMods/RFToolsPower/issues/52

**Comment by McJty** [comment]
Will fix this in a moment. Hang on

**Comment by McJty** [comment]
Fixed
