### ISSUE TITLE
client not connecting to server

### ISSUE THREAD

**Issue by lebanni** [McJtyMods/RFToolsUtility#32]
Minecraft 1.15.2
forge-1.15.2-31.2.36.jar
rftoolsutility-1.15-2.1.7.jar
all of your other mods are last versions

the screen is stuck on "joining world".

[latest.zip](https://github.com/McJtyMods/RFToolsUtility/files/5125778/latest.zip)

The log file is huge (135 Mo), so I compressed it.

**Comment by McJty** [comment]
Should be fixed now. You'll have to update all my mods

**Comment by lebanni** [comment]
Now the server is crashing.

[crash-2020-08-26_19.24.10-server.txt](https://github.com/McJtyMods/RFToolsUtility/files/5131408/crash-2020-08-26_19.24.10-server.txt)
