### ISSUE TITLE
Issue with 1.15.2 server boot crashing

### ISSUE THREAD

**Issue by nanonestor** [McJtyMods/RFToolsUtility#35]
Modded server running 1.15.2 and forge 31.2.31 crashing upon startup attempt.
RfToolsUtility = rftoolsutility-1.15-2.1.8.jar

Crash report: https://pastebin.com/ZKA168v7

Log file: https://pastebin.com/NaF8F99K

**Comment by McJty** [comment]
This was fixed some time ago.
