### ISSUE TITLE
Game crashes at start

### ISSUE THREAD

**Issue by hodo1962** [McJtyMods/RFToolsUtility#36]
The game crashes during starting process. 
It seems to be something withe the syringe.

The error is reproducable. (Have tried it several times)
Without RFToolsutility the games starts without any problems.

Minecraft: 1.16.2
Forge:  33.0.20
McJtyLib: 1.16-5.0.4
RFToolsbase: 1.16-2.0.3-beta
RFToolsutility: 1.16-3.0.6-beta

Error Log: https://pastebin.com/fRex3gun

_Edit_: It doesn't work with Forge 33.0.21 - the same error.

**Comment by hodo1962** [comment]
Sorry, Haven't read that so has posted this error before.

**Comment by McJty** [comment]
Update your mods to latest

**Comment by hodo1962** [comment]
With Forge Version 33.0.22 it works. The game loads without problems. This issue can be closed. Thank you for looking at it.
