### ISSUE TITLE
[1.15.2] Inventory Checker on Powah Energizing Orb Crash

### ISSUE THREAD

**Issue by davqvist** [McJtyMods/RFToolsUtility#37]
https://pastebin.com/NHjRQaq9

If you place the Inventory Checker on the Energizing Orb from Powah and set the slot to higher to 7, you get the above crash.
Not sure if Powah's or RFTools' fault.

Forge 31.2.31
RFTools Utility 2.1.6

**Comment by McJty** [comment]
The problem is that you set a slot index that is invalid for the machine. It's my fault for not checking that. I will fix that for next release
