### ISSUE TITLE
Elevator

### ISSUE THREAD

**Issue by ArturilloD** [McJtyMods/RFToolsUtility#38]
The elevator block does not exist, nor can I find it in the files. Will they add it? And hopefully they carry dimensions in the future. Thanks in advance and greetings, great job by the way.

Versions:
Minecraft: 1.15.2

Forja: 31.2.36

CompatLayer (solo si está en Minecraft 1.10 o 1.11):

McJtyLib: 4.1.7

RftoolsUtility: 2.1.9

RFToolsBase: 1.1.6

**Comment by McJty** [comment]
It will be ported eventually. Just didn't get around to it yet

**Comment by ArturilloD** [comment]
Well thank you very much, I understand that it can be a complex task. I
imagine it refers to the elevator, regarding the mod of dimensions I know
that it is not the right channel, sorry. If you need a guinea pig I can
help you, heh. Greetings and patience.

**Comment by ArchAngel727** [comment]
Any news

**Comment by McJty** [comment]
No sorry. Will come eventually but I have a lot of other things to do

**Comment by iggy-dave** [comment]
Any updates on this? No other mods have even came close to how good this elevator was =[

**Comment by kymppi** [comment]
Any news?

**Comment by bastirlnd** [comment]
Any updates on this issue? @McJty

**Comment by McJty** [comment]
Please don't ask about this. It will be ready when it's ready. I can't put
any time on this


Op zo 17 apr. 2022 19:55 schreef Bastian Rueland ***@***.***>:

**Comment by McJty** [comment]
This now present in 1.18 and 1.19. It's part of RFTools Builder but it's completely different

**Comment by Boolyman** [comment]
> It will be ported eventually. Just didn't get around to it yet

2 years later... Still waiting on this port.

**Comment by McJty** [comment]
Didn't you see my previous message? It is ported in 1.18 and higher. But it's called a mover now and it works totally differently

**Comment by McJty** [comment]
@Boolyman

**Comment by UlakayOutcast** [comment]
It is a pity that this is not at 1.16.5
