### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by Sunekaer** [McJtyMods/RFToolsUtility#39]
1.16.2-33.0.22

restrictions-1.16-3.0.1-beta.jar
rftoolsbase-1.16-2.0.3-beta.jar 
rftoolsbuilder-1.16-3.0.3-beta.jar
rftoolscontrol-1.16-4.0.3-beta.jar 
rftoolspower-1.16-3.0.4-beta.jar
rftoolsstorage-1.16-2.0.3-beta.jar
rftoolsutility-1.16-3.0.5.jar

https://pst.ksun.io/azuzeqodeg.rb

**Comment by McJty** [comment]
Update rftoolsutiliy to latest

**Comment by Sunekaer** [comment]
Ah twitch launcher showed as fully updated but there is a newer on CF...
