### ISSUE TITLE
[1.15.2] fml init error

### ISSUE THREAD

**Issue by joinmod** [McJtyMods/RFToolsUtility#40]
so tried start mc after update mcjtylib and rftools after that fml crashing with reason java.lang.RuntimeException: java.lang.reflect.InvocationTargetException caused by rftoolsutil 2.1.6.
forge-31.2.36
[crash logs](https://gist.github.com/joinmod/2f337bc9ac12ff346dabb3addf8925ae)

**Comment by McJty** [comment]
Update RFTools Utility to latest
