### ISSUE TITLE
[1.16.3] Shield Projectors can't be infused, can't be upgraded if has nbt

### ISSUE THREAD

**Issue by WhitePhant0m** [McJtyMods/RFToolsUtility#44]
![image](https://user-images.githubusercontent.com/33400200/95674136-eb072700-0bb6-11eb-9972-d55906a62bc8.png)
![image](https://user-images.githubusercontent.com/33400200/95674154-f6f2e900-0bb6-11eb-92e5-2c67b053d6bc.png)
![gif](https://i.gyazo.com/8403d684faf2133b546af5dc186c6b7a.gif)
![gif](https://i.gyazo.com/a1d024fefdd213b3e272c6a0eba072e6.gif)
Recipe works as intended if it doesn't have nbt.

**Comment by McJty** [comment]
I will check it out soon

**Comment by McJty** [comment]
Both bugs will be fixed next version. Thanks for reporting. BTW, you used the wrong github. The shield projector is part of RFToolsBuilder
