### ISSUE TITLE
[1.15.2] Cannot bind Redstone Screen Module to any block or frequency

### ISSUE THREAD

**Issue by Xiaminou** [McJtyMods/RFToolsUtility#49]
Sneak right-clicking it on blocks or Redstone Transmitters clears the module.

Minecraft: 1.15.2
Forge: 31.2.45
RFToolsUtility: 2.1.12
Mods: [129](https://pastebin.com/97iuPLhS)

**Comment by Topey2X** [comment]
Can confirm this happens in All The Mods 6 1.2.1

Minecraft: 1.16.3
Forge: 31.1.25
RFToolsUtility: 1.16-3.0.12

Strangely the button module has no trouble binding but doesn't unbind if you right click on empty air? Not sure if that's related but it's not as big of a deal.

**Comment by McJty** [comment]
Fixed in the version I released right now. Even if you were able to bind the channel it wouldn't have worked because I forgot to port some code from 1.12 here :-)
