### ISSUE TITLE
(forge-14.4) Error executing task on Client java.lang.NullPointerException: Must provide server when creating world

### ISSUE THREAD

**Issue by SDUBZ** [McJtyMods/RFToolsUtility#5]
Forge: 28.1.85
rfutils: rftoolsutility-1.14-1.2.7-alpha
client log: 
[latest.log](https://github.com/McJtyMods/RFToolsUtility/files/3823112/latest.log)

server:
[latest.log](https://github.com/McJtyMods/RFToolsUtility/files/3823117/latest.log)

**Comment by McJty** [comment]
When doing what?

**Comment by SDUBZ** [comment]
when i joined a dedicated server it kicked me out and gave me this

**Comment by SDUBZ** [comment]
now its giving me Received invalid discriminator byte 52 on channel rftoolsutility:rftoolsutility
16:52:27.622
Unknown custom packet identifier: rftoolsutility:rftoolsutility

**Comment by McJty** [comment]
Try updating. Just released new versions of everything

**Comment by SDUBZ** [comment]
getting same out put but diff code 

Received invalid discriminator byte 55 on channel rftoolsutility:rftoolsutility

with 
mcjtylib-1.14-3.5.11-alpha
rftoolsutility-1.14-1.2.8-alpha
rftoolsstorage-1.14-0.0.3-alpha
rftoolsbuilder-1.14-1.2.7-alpha
rftoolsbase-1.14-0.0.8-alpha

server side is affected @McJty

**Comment by McJty** [comment]
I don't understand why you're having these issues. My mods work fine on the Forgecraft server

**Comment by McJty** [comment]
Also can you give me a bit more of the server log?

**Comment by SDUBZ** [comment]
yes i will a few seconds

**Comment by SDUBZ** [comment]
Keep in mind mcjty more mods and more chances of incompat or cross code of some kind
Server logs:

[debug.log](https://github.com/McJtyMods/RFToolsUtility/files/3826982/debug.log)
[latest.log](https://github.com/McJtyMods/RFToolsUtility/files/3826983/latest.log)

**Comment by McJty** [comment]
None of these logs contain the invalid discriminator message?

**Comment by SDUBZ** [comment]
[latest.log](https://github.com/McJtyMods/RFToolsUtility/files/3827010/latest.log)
thats on the client for some reason

**Comment by McJty** [comment]
The reason for this problem has most likely been identified. A fix will soon follow

**Comment by McJty** [comment]
Hopefully fixed. Reopen if you still have issues

**Comment by SDUBZ** [comment]
it keeps mentioning a descriminator in console

**Comment by McJty** [comment]
Last update should fix this. Let me know if it doesn't and show me the full server log in that case
