### ISSUE TITLE
Energy Screen Module is capped at 2^32

### ISSUE THREAD

**Issue by Xiaminou** [McJtyMods/RFToolsUtility#50]
I'm using the Energy Screen Module to read the Energy Level of an Induction Matrix from Mekanism which currently holds 25.6 GFE however it seems the Energy Screen Module can only read numbers up to 2^32, which means it stops at 2.1 GFE (even in compact mode).

**Comment by McJty** [comment]
That's because FE itself is limited at 32-bits. Nothing I can do about that. GFE is something special from Mekanism
