### ISSUE TITLE
Shield ignores texture options

### ISSUE THREAD

**Issue by Nagispace** [McJtyMods/RFToolsUtility#51]
# Infos
Minecraft 1.16.3
FML : 34.1.25
rftolsbase : 1.16-2.0.6
rftoolsbuilder : 1.16-3.0.8
rftoolspower : 1.16-3.0.8
rftoolscontrol : 1.16-4.0.5
rftoolsstorage : 1.16-2.0.5
rftoolsutility : 1.16-3.0.11
optifine : 1.16.3_HD_U_G3 - forge mod version
## What I expect 
Being able to change the shield texture using the according option in the shield projector tier 4
## What happens
The setting is ignored

![image](https://user-images.githubusercontent.com/65559593/98464145-1b93ae00-21c1-11eb-8524-141ebc2206e3.png)
![image](https://user-images.githubusercontent.com/65559593/98464158-2e0de780-21c1-11eb-881e-bd9a93149f04.png)

**Comment by McJty** [comment]
Did you toggle the shield on/off? That's required to force an update

**Comment by Nagispace** [comment]
Yes
Right now I'm trying to run a newer version of optifine and if I get no results I'll try without it

**Comment by McJty** [comment]
This was fixed some time ago
