### ISSUE TITLE
1.15 - 2.1.15 - Rf Crafter duping Items in internal inventory on shift click

### ISSUE THREAD

**Issue by MagnificientLlama** [McJtyMods/RFToolsUtility#52]
While playing ATM5 (both before and after manually updating RFTools Utility) while shift clicking inside of an inventory with a stackable item, the item would move into another tile while doubling the size of it stack up to max stack number. 

This dupe is not purely visual.
**Before shift-clicking**
![image](https://user-images.githubusercontent.com/37192877/99112211-9b6cae80-25ed-11eb-87b4-a456d519764f.png)
**After shift-clicking** 
![image](https://user-images.githubusercontent.com/37192877/99112270-b2130580-25ed-11eb-8d96-be35f7205c8e.png)

Tested on both Tier 1 and Tier 3 crafter

**Comment by McJty** [comment]
I cannot reproduce this. Do you have inventory tweaks installed perhaps? Or some other mod that interpheres with inventories?

**Comment by MagnificientLlama** [comment]
As I have said, I am playing on server that is running All the mods 5 (clustercluck i know) There are multiple mods that interphere including inventory tweaks.( invtweaks-1.15.2-2.0.9) I think it would take a bit too much work to write out all the mods in the modpack here so ill just add a[ link](https://www.curseforge.com/minecraft/modpacks/all-the-mods-5/relations/dependencies) to relations in curseforge

**Comment by MagnificientLlama** [comment]
Looks like it was a bug that was due to ATM5 not updating it's mods and running old version of McJtyLib - prob fixed in version 1.15 https://github.com/McJtyMods/McJtyLib/commit/e5eff96b92efd3d62e88b765d2dca581025b838a
