### ISSUE TITLE
Modular storage destroying/duping items

### ISSUE THREAD

**Issue by officialGerero** [McJtyMods/RFToolsUtility#53]
So there i was playing ATM6, wanted to sort my inv (using inv tweaks) while i was in modular storage gui. I middle clicked to sort, items from storage module got replaced with items in my inventory. As storage module was almost full (300 stacks) it deleted most of my items and module itself gave me half of inventory of ores also deleted storage module itself. When i tried to reproduce: if my inv isn`t full it gives me items that were in storage module(if they all fit) including storage module, but doesn`t remove items from module. So i get items to my inv and the same items are still in the module. Hope that covers it

Before sorting my inv
![image](https://user-images.githubusercontent.com/40302455/99238488-743afa80-2802-11eb-8d6d-4815e435101b.png)
after i sorted
![image](https://user-images.githubusercontent.com/40302455/99238498-78671800-2802-11eb-8089-d4307691fc3f.png)
and ive put storage module back into modular storage
![image](https://user-images.githubusercontent.com/40302455/99238509-7b620880-2802-11eb-94e9-43a3720cabc3.png)

**Comment by McJty** [comment]
That's inventory tweaks messing with this. Not sure where the fault is but inventory tweaks and modular storage don't go together at this moment

**Comment by officialGerero** [comment]
Should i post something similar to inv tweaks git? Yea probably, i thought mb u can limit usage of it yourself

**Comment by officialGerero** [comment]
At least now people will know what not to do

**Comment by McJty** [comment]
I'd like to resolve this issue with inv tweaks. Can you make an issue there and link that issue here? Thanks

**Comment by officialGerero** [comment]
https://github.com/reo-ar/InvTweaksRenewed/issues/26 there u go, have a nice day

**Comment by McJty** [comment]
Will be fixed next release (by changing how modular storage works, new lock mode)
