### ISSUE TITLE
Crafter Severely broken...no player inventory showing and lost stored recipes display 

### ISSUE THREAD

**Issue by IamStig** [McJtyMods/RFToolsUtility#54]
RFtools Utility 1.16-3.0.17
RFTools base 1.16-2.0.6
McjtyLib 1.16-5.0.12
MC ver 1.16.3
forge-34.1.32
I have a Tier 3 Crafter setup, converting all MA essence to Supreme, I went to access it to manually put essence in but could not see my player inventory items. THIS IS ONLY A VISUAL BUG.... they are there and I managed to get the essence in by placing them in my slot 1 and clicking the seemingly empty slot when in the crafter UI. Also the saved crafts show in the left panel but are not showing up in the right panel where the recipes are learned...probably also just visual but not sure and make it unusable

Edit- This is odd. I just realised I had another crafter (They are both T3 BTW) that is attached to an RS crafter and doing Minecolony crafts with the Structurise Building tool. It is operating correctly. The crafter that is doing the essence has input and output via modular routers, the one doing the Minecolony crafting is input RS crafter output Modular Routers. The only other interaction is they are both connected to Cyclic cables for power. I doubt even you can work out this one. ;)

**Comment by McJty** [comment]
Can you give me some logs?

**Comment by IamStig** [comment]
I can give you a bit more info that I just discovered.....in the crafter with the structurise tool .... if I left click the tool in the RFTools crafter's storage area ...the crafting recipe area and the player inventory disappear.....but also the FTB chunks icon in top left of screen goes away ....they come back when I left click the tool again. Clicking empty slots does not do it and the other crafter clicking the master crystal slot show and hides the crystal and shows and hides the other items in the crafters inventory (essence) BUT opposite to when the crystal is visable. Also the FTB chunks icon is not displayed at any time when in that crafters UI. I will see what I can do for logs

**Comment by IamStig** [comment]
OK so I took a while getting back....I remember that I had OptiForge and Optifine installed and decided to remove them to see if that could be the problem, when I went back in and clicked on the structurize tool like I had been doing ....I crashed. Maybe this is helpful... 

[crash-2020-11-18_16.28.38-client.txt](https://github.com/McJtyMods/RFToolsUtility/files/5557980/crash-2020-11-18_16.28.38-client.txt)

**Comment by McJty** [comment]
Ok, you need to update McJtyLib

**Comment by IamStig** [comment]
Ah. Ok Thanks. BTW I readded the optifine and OptiForge and it went back to the previous behavior ...and not crashing. I will update McLib and let you know if it is resolved.

**Comment by IamStig** [comment]
Genius! The odd thing is I actually downloaded .13 2 days ago but never got it into the mods folder. I guess it got lost in the 1.16.3 1.16.4 transition frustration. 25 of the 126 mods I have don't had or easily identify a 1.16.4 version and some of the 101 that are 1.16.4 are hard coded and I can't use on my 1.16.3 stranded pack. But that's all part of the joy I guess. Thanks again
