### ISSUE TITLE
[1.16.4] Spawner does not show what is needed to spawn mobs

### ISSUE THREAD

**Issue by Pdiddy973** [McJtyMods/RFToolsUtility#55]
the Spawner does not show what is needed to spawn the mobs, i have tried re downloading the mod for both the client/server and also removed optifine and it still will not show
![image](https://user-images.githubusercontent.com/68764896/100827724-681e8200-342b-11eb-8546-3d485eccdd50.png)

**Comment by McJty** [comment]
Hmm I cannot reproduce this. Can you perhaps try to reset/remove the rftools utility config files (both client side in config folder as well as server-side in your world folder) and see if that fixes things?

**Comment by Pdiddy973** [comment]
Still the same, this is in the ATM 6 Mudpack if that helps, i have the config files as well if you wold like. i also tried a full reinstall of the mod pack client and server side.

**Comment by McJty** [comment]
What version of RFTools Utility is in that modpack?

**Comment by Pdiddy973** [comment]
also i just tried, if you supply it all the required items in the matter beamer it will consume them and RF and acts as if it is working but no spawns 

RFTools Util ver 1.16-3.0.18
RFTools Base ver 1.16-2.0.7

**Comment by MissRobyn102** [comment]
Hi McJty. I am having the same issue. Both on a server and in a single player game. I have deleted the config but that didnt help. I have also tried to update from 1.16-3.0.18 to 1.16-3.0.19. This didnt help. Attached it is a pictures of the syringe in the spawner
![2020-12-11_14 57 44](https://user-images.githubusercontent.com/44685746/101958880-76099b00-3bc1-11eb-86af-d402115912eb.png)
![2020-12-11_14 57 25](https://user-images.githubusercontent.com/44685746/101958882-773ac800-3bc1-11eb-8d9a-17861c85762e.png)
![2020-12-11_14 57 31](https://user-images.githubusercontent.com/44685746/101958884-773ac800-3bc1-11eb-857b-53e445a77e95.png)

**Comment by otDan** [comment]
Having the same issue in Enigmatica 6
Everything is default: 
![immagine](https://user-images.githubusercontent.com/59731738/101986968-89843700-3c91-11eb-9e1c-b8ece0121e4a.png)

**Comment by otDan** [comment]
Versions:
RFToolsUtility: 1.16-3.0.18
RFToolsBase: 1.16-2.0.7

**Comment by otDan** [comment]
Also as already said doesn't spawn mobs

**Comment by Taylantz** [comment]
Same problem here added the mods to Valhelsia 3 modpack 

rftoolsbase-1.16-2.0.8.jar
rftoolsbuilder-1.16-3.0.12.jar
rftoolsutility-1.16-3.0.19.jar

Nothing gets logged on the server or client-side as warn or error message

![Image of Yaktocat](https://i.imgur.com/dB02QMD.png)

**Comment by McJty** [comment]
To everyone here reporting this issue. When you say you deleted the config what config do you mean? The config that is relevant here is the one that is stored within your world itself (that's new since 1.15+). Try removing that one instead. Or else try if you can reproduce this problem on a new created world

**Comment by MissRobyn102** [comment]
So deleting all the RF configs did make the spawner work. Ty McJty

**Comment by Pdiddy973** [comment]
deleting all the configs this time, not just the RF tools utility, still did not resolve this issue for me, also making a new world does not resolve as well.

**Comment by McJty** [comment]
@Pdiddy973 but that's not what I asked. I asked if you also deleted the configs in your world folder. NOT the ones in the config directory

**Comment by Pdiddy973** [comment]
I am removing them from the world folder, the first time just  the RFtools base and RF tools utils, this time all of the RFtools configs. I tried it in a single player world and it wasn't working either. But after trying that it worked properly on my server...not sure what changed since after deleting the cfgs in my server world folder didn't initially resolve it but loading the single player than back to the server, the server spawner was working

**Comment by Poke5555** [comment]
i am also having this problem with using the DW20 1.16.4 modpack with rftoolsutility-1.16-3.0.19
ive deleted the configs on the client and server in and out of the world folder and i still cant get it working.

**Comment by McJty** [comment]
I think I'm going to rewrite how this configuration for the spawner works because it seems to be problematic for some

**Comment by WhiteGundalf** [comment]
> i am also having this problem with using the DW20 1.16.4 modpack with rftoolsutility-1.16-3.0.19
> ive deleted the configs on the client and server in and out of the world folder and i still cant get it working.

I could fix the issue with the same modpack and version by only deleting the "{savename}\serverconfig\rftoolsutility-server.toml" file and letting the server regenerate it.

**Comment by McJty** [comment]
The new release of RFTools Utility no longer has this problem. The entire config system for mobs has been removed. Instead the configuration is done using a much more stable recipe system. So every spawner entry is now a recipe that can be altered using regular resource packs
