### ISSUE TITLE
Duplication Bug in 1.15.2

### ISSUE THREAD

**Issue by Klodobe** [McJtyMods/RFToolsUtility#56]
I've been playing in the All The Mods 5 ModPack so I am not certain if it exclusive to this pack of it is an issue in general.

If using any of the (Auto) Crafters and shift-click a stackable item that isn't already in a full stack it will double the item count of that item.

**Comment by McJty** [comment]
I think that bug was fixed some time ago. I think this modpack is using outdated mods
