### ISSUE TITLE
Crafter GUI Weirdness

### ISSUE THREAD

**Issue by aaronhowser1** [McJtyMods/RFToolsUtility#63]
![image](https://user-images.githubusercontent.com/15698722/104630752-cd87a480-5660-11eb-81e5-47a55d3a52e2.png)
![image](https://user-images.githubusercontent.com/15698722/104630769-d4161c00-5660-11eb-88f5-ed34ca1a3540.png)
![image](https://user-images.githubusercontent.com/15698722/104630780-d9736680-5660-11eb-927a-25a0e9db8be2.png)

After clicking the top slot
![image](https://user-images.githubusercontent.com/15698722/104630795-e1cba180-5660-11eb-9fef-58de9c3fc985.png)
"All" stays after moving away

![image](https://user-images.githubusercontent.com/15698722/104630814-ebeda000-5660-11eb-8664-e82a4185baaa.png)
then clicking:
![image](https://user-images.githubusercontent.com/15698722/104630838-f4de7180-5660-11eb-8aa1-c2ef5ce60613.png)
then clicking again:
![image](https://user-images.githubusercontent.com/15698722/104630877-058ee780-5661-11eb-80b4-d67aebdf0d9c.png)

After leaving GUI (then powering) then reopening:
![image](https://user-images.githubusercontent.com/15698722/104630945-20f9f280-5661-11eb-915d-5a53d837680a.png)
the buttons have no text again

**Comment by McJty** [comment]
The gui and integration with JEI will improve next release
