### ISSUE TITLE
[1.16] Simple Dialer not remembering it's settings on reload

### ISSUE THREAD

**Issue by Susjin** [McJtyMods/RFToolsUtility#65]
Issue description: 
Exactly what is in the title

Steps to reproduce: 
1. Get a Transmitter and Receiver working
2. Dial the Transmiter to the Receiver
3. Shift-Rightclick the transmitter with the Simple Dialer in hand
4. Place the Dialer in the world
5. Close and re-open Minecraft
6. Simple Dialer settings will be "unset"

Versions:
* Minecraft: 1.16.4
* Forge: 1.16.4 - 35.1.36
* McJtyLib: 1.16-5.0.15
* RFToolsBase: 1.16-2.0.9

PS: I'm using the DW20 pack, if you can't reproduce it, maybe it's some kind of mod incompatibility

**Comment by McJty** [comment]
I can reproduce this. Debugging now

**Comment by McJty** [comment]
Fixed next release
