### ISSUE TITLE
Feature request ...possibly just a "Wire" Ui

### ISSUE THREAD

**Issue by IamStig** [McJtyMods/RFToolsUtility#66]
What I was  originally looking for was a one-way redstone item that retains the redstone signal sequence.
That is if placed in a line of 16 redstone that has a lever on one end the last one would show 0. A repeater restarts the signal at 15, your RFTools Wire item puts out the signal that goes into it, effectively meaning our last redstone would be 2.
The purpose is to be able to add a one way point into a system with 2 redstone sources converging and not have the stronger signal go back up stream on the other input.
My original idea was to have an item that simply subtracted 2 from the input level...so 10 before the block becomes 8 after the block, meaning our 16th redstone would be 0. But I thought there might be more uses for a block that can be configured....allowing an input of say 15 going in, setting the variable to 14 would put the output to 1. This would allow redstone constructions to be greatly compacted.
Which is why I thought a UI in your RFTools Wire that defaults to zero but can be altered to +/- 15 would be the best option ...........I know -15 would give zero but with +15 it could be used as a repeater, then again we have a repeater so maybe +/-14. Just an idea, would likely take less time to implement than to decipher my ramblings. ¯\_(ツ)_/¯

**Comment by McJty** [comment]
This is confusing. I'm not sure I understand your idea and why this can't already be done with the logic blocks we already have?

**Comment by IamStig** [comment]
Sorry it is hard to be brief and get the idea across.
I had a look again at the logic and analog blocks but they don't seem to do what I am wanting, so far as I can tell they take 2-3 inputs and output a value 15 signal when certain criteria is met, I am after an output based on input signal. So I'll try an image to show what got me looking.

The image is my Botania setup. The comparator gives a redstone value for the mana pool and that outside redstone path is 15 to stop dropping charcoal when the pool is full (right side transmitter) AND it stops TNT placement when the pool is 2/3 full by the bottom transmitter. The middle line (mostly repeaters) stops charcoal and TNT while mana is being passed through the Mana detector (between mana spreader & pool). When the middle line is active it is a strong signal that goes in both direction from the intersection (without the Wire). The RFTools Wire is almost what I need but I needed to move the transmitter at right back 2 because the wire not only doesn't reduce the signal by 1 like the redstone it replaced but it outputs the signal that went in so the output is 2 higher. It has also meant that 2 TNT get placed instead of 1 (not sure why) but I always play safe ...so 3 Entropinnyum to be sure.

The used to be a block from Draconic that can place beside a comparator in subtract mode and it would subtract whatever value you set (0-15) so the comparator would if set to 14 only emit when the input was 15. This is what I thought might be achievable in 1 block by adding a UI to the Wire that did that. 
![2021-02-07_00 37 15](https://user-images.githubusercontent.com/20489424/107119640-0e2fb200-68dd-11eb-82b6-5567e6ced180.png)

This 2nd image shows a simplistic view of what redstone does as opposed to what the Wire does. In this example I am looking for a block that would let me have a 7 output from the block that also stops a signal going back towards the lever (if there was an intersection with a stronger signal)
![2021-02-06_15 18 10](https://user-images.githubusercontent.com/20489424/107121034-6322f680-68e4-11eb-81ca-f6d4febab6f2.png)

I don't know if that is any clearer, I think I am more confused ..then again it is past 1.30am here
