### ISSUE TITLE
Screen RF Module on Mek Induction cell not working above 2.1GRF

### ISSUE THREAD

**Issue by KriKri98** [McJtyMods/RFToolsUtility#69]
As the title says, the power module does work perfectly fine if the total power of the induction cell is below 2.1 GRF. Above that value, rf/t goes to 0 and RF stops at 2.1 GRF.

![2021-03-03_12 28 38](https://user-images.githubusercontent.com/46320871/109804259-57e09380-7c22-11eb-83b1-7c67e31a5114.png)
Screen work fine, power bar at near max.

![2021-03-03_12 21 11](https://user-images.githubusercontent.com/46320871/109804371-747ccb80-7c22-11eb-8e95-2b05271b6265.png)
Screen stopped working, power bar at max.

**Comment by KriKri98** [comment]
I am on the Direwolf20 1.16 modpack and I am unable to update forge and mods.
rftools utility: 1.16-3.0.20

**Comment by McJty** [comment]
That's normal. The RF API only goes to 2Gig. Mekanism is cheating. Can't help that
