### ISSUE TITLE
Matter beamers do not connect to spawner

### ISSUE THREAD

**Issue by gCoreByte** [McJtyMods/RFToolsUtility#70]
![image](https://user-images.githubusercontent.com/21132799/110217261-bc6a4f80-7ebb-11eb-85ec-587f209aa0c5.png)
![image](https://user-images.githubusercontent.com/21132799/110217271-c55b2100-7ebb-11eb-8c63-96ac08151c51.png)
![image](https://user-images.githubusercontent.com/21132799/110217275-c8561180-7ebb-11eb-8025-999cef3adbca.png)
![image](https://user-images.githubusercontent.com/21132799/110217284-d1df7980-7ebb-11eb-942a-a1a871f16819.png)

Connecting the beamers to the spawner does nothing. In chat it says destination set, but there is no visual confirmation. They are all filled with power and items. Spawning does not work with or without water infront of the spawner.

base 2.0.10
utility 3.0.23

**Comment by McJty** [comment]
I don't see where you are giving the matter beamers a redstone signal?
