### ISSUE TITLE
Elevator Block for 1.16?

### ISSUE THREAD

**Issue by Minecraft2p0** [McJtyMods/RFToolsUtility#71]
I loved the Elevator Block for 1.12.2.
I hope this epic element comes in 1.16.5 too. 

Is it planned? 

Greetings

**Comment by McJty** [comment]
It's planned

**Comment by iggy-dave** [comment]
Any update on the elevator block making a return?

**Comment by McJty** [comment]
Eventually. Might take a while. I have a lot to do on my mods

**Comment by McJty** [comment]
I implemented this for 1.18+
