### ISSUE TITLE
Server-side NullPointerException when using dialing device

### ISSUE THREAD

**Issue by nrllewellyn** [McJtyMods/RFToolsUtility#73]
Issue description: When accessing a dialing device, no destinations are shown and an exception is thrown server-side. (See "relevant logs" below). This may be related to issue #60. 

Steps to reproduce: Can't reproduce in a single player world. On server, placing down and accessing any dialing device causes the problem to occur. 

Versions:
* Minecraft: 1.16.5
* Forge: forge-1.16.5-36.0.45.jar
* CompatLayer (only if on Minecraft 1.10 or 1.11): n/a
* McJtyLib: mcjtylib-1.16-5.0.17.jar
* RFTools: 
  * rftoolsbase-1.16-2.0.10.jar
  * rftoolsutility-1.16-3.0.23.jar

Relevant logs, if any: https://pastebin.com/ssHQDSLg

**Comment by McJty** [comment]
This has been fixed a while ago. Forgot to close this
