### ISSUE TITLE
Crash report upon using RFtools util transmitter and receiver 

### ISSUE THREAD

**Issue by mcintosh109** [McJtyMods/RFToolsUtility#75]
Issue description: game crash upon arriving on a Rftools receiver while having mek radiation possable AE2 confilct

Steps to reproduce:
1.get radiation on plyer
2. use the rf tools transmitter and recever
3.game crash 
Versions:
Pack: DW1.16.5 Pack Ver1.7.0
Forge: forge-1.16.5-36.0.45
Mekanism-1.16.5-10.0.21.448
Rftoolsutility-1.16-3.0.23
appliedenergistics2-8.3.0-alpha.1

crashlog online ----> https://paste.ee/p/BRrpp
[Crashreport 3.15.21.txt](https://github.com/McJtyMods/RFToolsUtility/files/6145132/Crashreport.3.15.21.txt)

will upload to mekanism AE2 crash report as well

**Comment by mcintosh109** [comment]
conflict was determined to not involve Mekanism by there dev team

**Comment by McJty** [comment]
The crash is in AE2 though (which is unrelated to Mekanism and RFTools Utility). So did you report to them?

**Comment by mcintosh109** [comment]
yep seems they are aware and they found a fix
