### ISSUE TITLE
Can not auto craft Ex Nihilo: Sequentia

### ISSUE THREAD

**Issue by NJM1564** [McJtyMods/RFToolsUtility#78]
The RFtools Crafters will not craft any ore pieces into the ores they are supposed to make.
It will craft the various forms of Pebbles into cobble derivatives.

**Comment by McJty** [comment]
Please make useful bug reports. I need a version. I need exact steps of what you're doing. I can't do anything with something vague like this

**Comment by beefql** [comment]
I am having a similar issue where the RFTools Tier 3 Crafter will not make Iron Ore out of four Iron Ore Pieces, the crafting recipe from Ex Nihilo: Sequentia in Sky Bees.  I believe this is more an issue with the overridden recipe in Sky Bees than it is with RFTools Utilities.  When I start a new Minecraft instance with RFTools Utilities and Ex Nihilo: Sequentia I am able to use the Crafter to make Iron Ore Chunks out of the four Iron Ore Pieces.

**Comment by McJty** [comment]
Closing because of severe lack of information (people! Without a version and logs I can't do anything!)
