### ISSUE TITLE
Screen crashes client

### ISSUE THREAD

**Issue by xxkainexx** [McJtyMods/RFToolsUtility#8]
The rftool's screen crashed when placed, but was actually placed so when logging in again it crashes again. I have attached a crash report.
[crash-2019-11-28_21.49.42-client.txt](https://github.com/McJtyMods/RFToolsUtility/files/3903686/crash-2019-11-28_21.49.42-client.txt)

**Comment by McJty** [comment]
This started happening at forge version 28.1.56. I'm investigating what to do about it

**Comment by McJty** [comment]
As a workaround you may have some luck setting this option to false in rftoolsutility-client.toml:

	useTruetype = false

**Comment by McJty** [comment]
This is a bug in Forge and will be fixed when this is merged in forge:
https://github.com/MinecraftForge/MinecraftForge/pull/6337
