### ISSUE TITLE
[1.16.5] Java Crash in Button Module

### ISSUE THREAD

**Issue by NielsPilgaard** [McJtyMods/RFToolsUtility#82]
Relayed from: https://github.com/NillerMedDild/Enigmatica6/issues/2287

> **Describe the bug**
> I was using the RF tools screen with a buton module in it, when i tried typing in the lable bar my game crashed
>
> **Logs**
> Input pastebin link to crash-report or `latest.log`, if applicable.
> [hs_err_pid9264.log](https://github.com/NillerMedDild/Enigmatica6/files/6557159/hs_err_pid9264.log)

It appears that some parts of the Button Module is incompatible with Java 11, as far as I can see?

**Comment by McJty** [comment]
You'll have more possible problems on java 11. I strongly recommend java 8

**Comment by NielsPilgaard** [comment]
For the most part Java 11 works just fine, most mods seem to support it at this point. But I totally understand if you only support Java 8.

**Comment by NielsPilgaard** [comment]
Java 8 fixed that particular problem, but changing the font on a text module also resulted in a java crash, with java 8:
https://gist.github.com/NillerMedDild/1908b9d5bdf7c7c97d2aab1ae210eadd

**Comment by NielsPilgaard** [comment]
Closing since this is ancient 😄
