### ISSUE TITLE
Crash sided_setup event phase

### ISSUE THREAD

**Issue by Seth0067** [McJtyMods/RFToolsUtility#84]
Howdy!

With the new versions dropped today...  

https://pastebin.com/08qHx4Mn

led to 

![mcjty](https://user-images.githubusercontent.com/22122348/124843386-d007ee80-df5f-11eb-9e3a-f65bfa9e8ac8.PNG)

Hope that is helpful!

**Comment by Seth0067** [comment]
[Here](https://pastebin.com/f7LHwf8j) is the crash report referenced as well.

**Comment by McJty** [comment]
I fixed this yesterday
