### ISSUE TITLE
Preview issues

### ISSUE THREAD

**Issue by DemonSlayer112** [McJtyMods/RFToolsUtility#89]
2 Issues, first, normal Shape Card for placing blocks will not preview from the builder.
If attempted it shows the preview then vanishes instantly.

Second issue, When a card does preview it allows you to x-ray blocks(shown in screenshot attachment)
![Screenshot (48749)](https://user-images.githubusercontent.com/70122500/126907848-18b7c01e-af1e-42d1-9cd1-1cfbf199ccaf.png)

**Comment by McJty** [comment]
Wrong mod. This should be in RFTools Builder

**Comment by McJty** [comment]
I can reproduce the xray problem but the preview mode works just fine with a normal shape card

**Comment by McJty** [comment]
XRay problem is fixed next release
