### ISSUE TITLE
Porter and Tank

### ISSUE THREAD

**Issue by IamStig** [McJtyMods/RFToolsUtility#9]
2 minor issues. The Advanced charged porter doesn't take on the Receiver name and does not accept typed name. When it is linked it says something like ..
Dimension DimensionType {minecraft:overworld}
.. there is more I think but even though a cursor appears it can't be moved.
The other on is the Tank, the box that displays the fluid render doesn't show anything until 5 buckets have been added. Also, while it does have a bar showing how full it is, can you add something to the UI that shows the amount of fluid it is holding please. At the moment TheOneProbe doesn't show a level for it.

PS This is on an old account name of
ockerspock o/

**Comment by IamStig** [comment]
Update on the tank.... it seems that it will show the fluid render if you have less fluid ...if you the area (simple block state update techniques don't do it) and return.

**Comment by McJty** [comment]
I'll check this out in a later fix. First need to do critical fixes. Thanks for reporting

**Comment by McJty** [comment]
The charged porter bug doesn't seem to be a thing anymore (after waiting long enough it fixed itself :-) )

Checking on the other bug

**Comment by McJty** [comment]
Tank issues will be fixed next release
