### ISSUE TITLE
looking at rftools environmental controller makes the screen have broken textures

### ISSUE THREAD

**Issue by chaosbolt99999** [McJtyMods/RFToolsUtility#92]
When looking at the rftools environmental controller the attached image happens and everything returns to normal when i look away.  
![image](https://user-images.githubusercontent.com/89195237/130055969-72f495dd-9615-4738-a4e7-5e7f9a68ddda.png)

**Comment by McJty** [comment]
Funky...

I would need to see a version though

**Comment by chaosbolt99999** [comment]
versions used:
mcjtylib-1.16-5.0.22
rftoolsutility-1.16-3.1.1
rftoolsbase-1.16-2.0.11

**Comment by McJty** [comment]
Do you have optifine or something? Never seen that before

**Comment by chaosbolt99999** [comment]
i tried it without optifine and that fixed it. thanks!
edit - the bug was probably caused from an outdated version of optifine since it went back to normal after updating
edit2 - the bug happens even with the updated version of optifine but only if its turned on. After removing optifine i found that there was supposed to be a light effect when the controller is powered on and that is the only time the bug happens

**Comment by McJty** [comment]
Why did you reopen it? I can't do anything about bugs related to optifine

**Comment by chaosbolt99999** [comment]
oh alright sorry ill close it again
