### ISSUE TITLE
Enviro Controller's Peaceful and Noteleport Modules do not work

### ISSUE THREAD

**Issue by aaronhowser1** [McJtyMods/RFToolsUtility#94]
![image](https://user-images.githubusercontent.com/15698722/134312478-d666e56d-9476-433d-8986-4a074054f1b7.png)
98 radius, y 1-70, the floor is at y=20. Mobs are still spawning.

![image](https://user-images.githubusercontent.com/15698722/134312611-a2686230-3e44-4e3e-86f9-80d5706fcc7d.png)
This used to be an endermen until i punched it and it teleported away. 
![image](https://user-images.githubusercontent.com/15698722/134312667-e614a73c-f127-4d13-a288-3b0a222d4c81.png)

This is using `rftoolsutility-1.16-3.1.2`

**Comment by McJty** [comment]
The peaceful module will be fixed next release
