### ISSUE TITLE
Screen energy module cant show large numbers

### ISSUE THREAD

**Issue by Kitzwildiff** [McJtyMods/RFToolsUtility#96]
I'm trying to show the energy of my Mekanism Induction Matrix on a Screen. But it shows 100% at 2147483647 FE, even though the Matrix can store much more energy. I guess this is because somewhere is worked with an Integer, but it should be a long (2147483647 is the max of an Integer).

**Comment by McJty** [comment]
Forge Energy uses integers. That's what the energy module is using. It can't know that some mods bypass this system to store more power
