### ISSUE TITLE
Crafter's Remember items button locks inventory

### ISSUE THREAD

**Issue by Wlnfr** [McJtyMods/RFToolsUtility#97]
### System information:
Minecraft: 1.16.5
Forge: 36.2.2
jei-1.16.5-7.7.1.118
mcjtylib-1.16-5.0.22
rftoolsbase-1.16-2.0.11
rftoolsutility-1.16-3.1.2
AdoptOpenJDK 11
Xeon x5460
GTX 650
### Description:
Clicking on the button after filling up every other slot that's not used for ingredients or output of set recipe with random items(cobble, stone, torches etc.) also locks up player's inventory. It becomes impossible to move items around in player's inventory with crafter GUI open unless it's an item that was remembered in crafter's buffers. I also recall this bug being present in 1.15 version
### Video demonstration:
https://user-images.githubusercontent.com/8050905/136450396-a6ec76c9-b9ad-4f22-b932-a175c2608e62.mp4

**Comment by LuciusV** [comment]
Same there, very annoying

**Comment by LuciusV** [comment]
I am surprised that this super annoying bug have been not fixed and even doesn't get feedback :(

**Comment by McJty** [comment]
These bugs have recently been fixed. Forgot to close this. Sorry
