### ISSUE TITLE
Game refuses to start on load, 1.16.5

### ISSUE THREAD

**Issue by avidbiscuit** [McJtyMods/RFToolsUtility#99]
First loading the game 1.16.5 with the RFTUtilities mod.
Using the HARDIS 1.16.5 mod alongside it as it is required as a dependency,
***Mod List***
![mod list](https://user-images.githubusercontent.com/50924190/137964708-69412157-283c-4839-8ffd-1b3e430e6928.PNG)
***Crash Log***
[RFTUtilities_CrashLog.txt](https://github.com/McJtyMods/RFToolsUtility/files/7375676/RFTUtilities_CrashLog.txt)
***Latest Log***
[RFTUtilities_LatestLog.txt](https://github.com/McJtyMods/RFToolsUtility/files/7375680/RFTUtilities_LatestLog.txt)
***Crash Screen***
![image](https://user-images.githubusercontent.com/50924190/137965055-82f57b91-99a6-457c-be65-7b6f1e53c64c.png)

Should you require anything else in regards to this crash please let me know and I will do my best to accommodate.

**Comment by McJty** [comment]
It seems like your version of forge is too old

**Comment by avidbiscuit** [comment]
> 
> 
> It seems like your version of forge is too old

Yes! Updated to newest version of Forge as of 20/10/2021.
Issue Closed
